// Code generated by ent, DO NOT EDIT.

package relaywalletledgerentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// RelayKeyID applies equality check predicate on the "relay_key_id" field. It's identical to RelayKeyIDEQ.
func RelayKeyID(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldRelayKeyID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldProjectID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldRequestID, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldUsageLogID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldAmount, v))
}

// BalanceBefore applies equality check predicate on the "balance_before" field. It's identical to BalanceBeforeEQ.
func BalanceBefore(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldBalanceAfter, v))
}

// UpstreamCost applies equality check predicate on the "upstream_cost" field. It's identical to UpstreamCostEQ.
func UpstreamCost(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldUpstreamCost, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldIdempotencyKey, v))
}

// OperatorUserID applies equality check predicate on the "operator_user_id" field. It's identical to OperatorUserIDEQ.
func OperatorUserID(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldOperatorUserID, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldUpdatedAt, v))
}

// RelayKeyIDEQ applies the EQ predicate on the "relay_key_id" field.
func RelayKeyIDEQ(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldRelayKeyID, v))
}

// RelayKeyIDNEQ applies the NEQ predicate on the "relay_key_id" field.
func RelayKeyIDNEQ(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldRelayKeyID, v))
}

// RelayKeyIDIn applies the In predicate on the "relay_key_id" field.
func RelayKeyIDIn(vs ...int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldRelayKeyID, vs...))
}

// RelayKeyIDNotIn applies the NotIn predicate on the "relay_key_id" field.
func RelayKeyIDNotIn(vs ...int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldRelayKeyID, vs...))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldProjectID, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotNull(FieldRequestID))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldUsageLogID, v))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotNull(FieldUsageLogID))
}

// DirectionEQ applies the EQ predicate on the "direction" field.
func DirectionEQ(v Direction) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldDirection, v))
}

// DirectionNEQ applies the NEQ predicate on the "direction" field.
func DirectionNEQ(v Direction) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldDirection, v))
}

// DirectionIn applies the In predicate on the "direction" field.
func DirectionIn(vs ...Direction) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldDirection, vs...))
}

// DirectionNotIn applies the NotIn predicate on the "direction" field.
func DirectionNotIn(vs ...Direction) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldDirection, vs...))
}

// SceneEQ applies the EQ predicate on the "scene" field.
func SceneEQ(v Scene) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldScene, v))
}

// SceneNEQ applies the NEQ predicate on the "scene" field.
func SceneNEQ(v Scene) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldScene, v))
}

// SceneIn applies the In predicate on the "scene" field.
func SceneIn(vs ...Scene) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldScene, vs...))
}

// SceneNotIn applies the NotIn predicate on the "scene" field.
func SceneNotIn(vs ...Scene) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldScene, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldAmount, v))
}

// AmountContains applies the Contains predicate on the "amount" field.
func AmountContains(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldContains(FieldAmount, v))
}

// AmountHasPrefix applies the HasPrefix predicate on the "amount" field.
func AmountHasPrefix(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldHasPrefix(FieldAmount, v))
}

// AmountHasSuffix applies the HasSuffix predicate on the "amount" field.
func AmountHasSuffix(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldHasSuffix(FieldAmount, v))
}

// AmountEqualFold applies the EqualFold predicate on the "amount" field.
func AmountEqualFold(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEqualFold(FieldAmount, v))
}

// AmountContainsFold applies the ContainsFold predicate on the "amount" field.
func AmountContainsFold(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldContainsFold(FieldAmount, v))
}

// BalanceBeforeEQ applies the EQ predicate on the "balance_before" field.
func BalanceBeforeEQ(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceBeforeNEQ applies the NEQ predicate on the "balance_before" field.
func BalanceBeforeNEQ(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldBalanceBefore, v))
}

// BalanceBeforeIn applies the In predicate on the "balance_before" field.
func BalanceBeforeIn(vs ...string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeNotIn applies the NotIn predicate on the "balance_before" field.
func BalanceBeforeNotIn(vs ...string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeGT applies the GT predicate on the "balance_before" field.
func BalanceBeforeGT(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldBalanceBefore, v))
}

// BalanceBeforeGTE applies the GTE predicate on the "balance_before" field.
func BalanceBeforeGTE(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldBalanceBefore, v))
}

// BalanceBeforeLT applies the LT predicate on the "balance_before" field.
func BalanceBeforeLT(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldBalanceBefore, v))
}

// BalanceBeforeLTE applies the LTE predicate on the "balance_before" field.
func BalanceBeforeLTE(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldBalanceBefore, v))
}

// BalanceBeforeContains applies the Contains predicate on the "balance_before" field.
func BalanceBeforeContains(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldContains(FieldBalanceBefore, v))
}

// BalanceBeforeHasPrefix applies the HasPrefix predicate on the "balance_before" field.
func BalanceBeforeHasPrefix(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldHasPrefix(FieldBalanceBefore, v))
}

// BalanceBeforeHasSuffix applies the HasSuffix predicate on the "balance_before" field.
func BalanceBeforeHasSuffix(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldHasSuffix(FieldBalanceBefore, v))
}

// BalanceBeforeEqualFold applies the EqualFold predicate on the "balance_before" field.
func BalanceBeforeEqualFold(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEqualFold(FieldBalanceBefore, v))
}

// BalanceBeforeContainsFold applies the ContainsFold predicate on the "balance_before" field.
func BalanceBeforeContainsFold(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldContainsFold(FieldBalanceBefore, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldBalanceAfter, v))
}

// BalanceAfterContains applies the Contains predicate on the "balance_after" field.
func BalanceAfterContains(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldContains(FieldBalanceAfter, v))
}

// BalanceAfterHasPrefix applies the HasPrefix predicate on the "balance_after" field.
func BalanceAfterHasPrefix(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldHasPrefix(FieldBalanceAfter, v))
}

// BalanceAfterHasSuffix applies the HasSuffix predicate on the "balance_after" field.
func BalanceAfterHasSuffix(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldHasSuffix(FieldBalanceAfter, v))
}

// BalanceAfterEqualFold applies the EqualFold predicate on the "balance_after" field.
func BalanceAfterEqualFold(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEqualFold(FieldBalanceAfter, v))
}

// BalanceAfterContainsFold applies the ContainsFold predicate on the "balance_after" field.
func BalanceAfterContainsFold(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldContainsFold(FieldBalanceAfter, v))
}

// UpstreamCostEQ applies the EQ predicate on the "upstream_cost" field.
func UpstreamCostEQ(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldUpstreamCost, v))
}

// UpstreamCostNEQ applies the NEQ predicate on the "upstream_cost" field.
func UpstreamCostNEQ(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldUpstreamCost, v))
}

// UpstreamCostIn applies the In predicate on the "upstream_cost" field.
func UpstreamCostIn(vs ...string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldUpstreamCost, vs...))
}

// UpstreamCostNotIn applies the NotIn predicate on the "upstream_cost" field.
func UpstreamCostNotIn(vs ...string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldUpstreamCost, vs...))
}

// UpstreamCostGT applies the GT predicate on the "upstream_cost" field.
func UpstreamCostGT(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldUpstreamCost, v))
}

// UpstreamCostGTE applies the GTE predicate on the "upstream_cost" field.
func UpstreamCostGTE(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldUpstreamCost, v))
}

// UpstreamCostLT applies the LT predicate on the "upstream_cost" field.
func UpstreamCostLT(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldUpstreamCost, v))
}

// UpstreamCostLTE applies the LTE predicate on the "upstream_cost" field.
func UpstreamCostLTE(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldUpstreamCost, v))
}

// UpstreamCostContains applies the Contains predicate on the "upstream_cost" field.
func UpstreamCostContains(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldContains(FieldUpstreamCost, v))
}

// UpstreamCostHasPrefix applies the HasPrefix predicate on the "upstream_cost" field.
func UpstreamCostHasPrefix(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldHasPrefix(FieldUpstreamCost, v))
}

// UpstreamCostHasSuffix applies the HasSuffix predicate on the "upstream_cost" field.
func UpstreamCostHasSuffix(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldHasSuffix(FieldUpstreamCost, v))
}

// UpstreamCostIsNil applies the IsNil predicate on the "upstream_cost" field.
func UpstreamCostIsNil() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIsNull(FieldUpstreamCost))
}

// UpstreamCostNotNil applies the NotNil predicate on the "upstream_cost" field.
func UpstreamCostNotNil() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotNull(FieldUpstreamCost))
}

// UpstreamCostEqualFold applies the EqualFold predicate on the "upstream_cost" field.
func UpstreamCostEqualFold(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEqualFold(FieldUpstreamCost, v))
}

// UpstreamCostContainsFold applies the ContainsFold predicate on the "upstream_cost" field.
func UpstreamCostContainsFold(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldContainsFold(FieldUpstreamCost, v))
}

// PriceSnapshotIsNil applies the IsNil predicate on the "price_snapshot" field.
func PriceSnapshotIsNil() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIsNull(FieldPriceSnapshot))
}

// PriceSnapshotNotNil applies the NotNil predicate on the "price_snapshot" field.
func PriceSnapshotNotNil() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotNull(FieldPriceSnapshot))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// OperatorUserIDEQ applies the EQ predicate on the "operator_user_id" field.
func OperatorUserIDEQ(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldOperatorUserID, v))
}

// OperatorUserIDNEQ applies the NEQ predicate on the "operator_user_id" field.
func OperatorUserIDNEQ(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldOperatorUserID, v))
}

// OperatorUserIDIn applies the In predicate on the "operator_user_id" field.
func OperatorUserIDIn(vs ...int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDNotIn applies the NotIn predicate on the "operator_user_id" field.
func OperatorUserIDNotIn(vs ...int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDGT applies the GT predicate on the "operator_user_id" field.
func OperatorUserIDGT(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldOperatorUserID, v))
}

// OperatorUserIDGTE applies the GTE predicate on the "operator_user_id" field.
func OperatorUserIDGTE(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldOperatorUserID, v))
}

// OperatorUserIDLT applies the LT predicate on the "operator_user_id" field.
func OperatorUserIDLT(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldOperatorUserID, v))
}

// OperatorUserIDLTE applies the LTE predicate on the "operator_user_id" field.
func OperatorUserIDLTE(v int) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldOperatorUserID, v))
}

// OperatorUserIDIsNil applies the IsNil predicate on the "operator_user_id" field.
func OperatorUserIDIsNil() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIsNull(FieldOperatorUserID))
}

// OperatorUserIDNotNil applies the NotNil predicate on the "operator_user_id" field.
func OperatorUserIDNotNil() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotNull(FieldOperatorUserID))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.FieldContainsFold(FieldRemark, v))
}

// HasRelayKey applies the HasEdge predicate on the "relay_key" edge.
func HasRelayKey() predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RelayKeyTable, RelayKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelayKeyWith applies the HasEdge predicate on the "relay_key" edge with a given conditions (other predicates).
func HasRelayKeyWith(preds ...predicate.RelayKey) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(func(s *sql.Selector) {
		step := newRelayKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelayWalletLedgerEntry) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelayWalletLedgerEntry) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelayWalletLedgerEntry) predicate.RelayWalletLedgerEntry {
	return predicate.RelayWalletLedgerEntry(sql.NotPredicates(p))
}
