// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "key", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"user", "service_account", "noauth"}, Default: "user"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "enabled"},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "profiles", Type: field.TypeJSON, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_projects_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[10]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "api_keys_by_user_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[11]},
			},
			{
				Name:    "api_keys_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[10]},
			},
			{
				Name:    "api_keys_by_key",
				Unique:  true,
				Columns: []*schema.Column{APIKeysColumns[4]},
			},
		},
	}
	// ChannelsColumns holds the columns for the "channels" table.
	ChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"openai", "openai_responses", "codex", "vercel", "anthropic", "anthropic_aws", "anthropic_gcp", "gemini_openai", "gemini", "gemini_vertex", "deepseek", "deepseek_anthropic", "deepinfra", "fireworks", "doubao", "doubao_anthropic", "moonshot", "moonshot_anthropic", "zhipu", "zai", "zhipu_anthropic", "zai_anthropic", "anthropic_fake", "openai_fake", "openrouter", "xiaomi", "xai", "ppio", "siliconflow", "volcengine", "longcat", "longcat_anthropic", "minimax", "minimax_anthropic", "aihubmix", "burncloud", "modelscope", "bailian", "jina", "github", "github_copilot", "claudecode", "cerebras", "antigravity", "nanogpt", "nanogpt_responses"}},
		{Name: "base_url", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "disabled"},
		{Name: "credentials", Type: field.TypeJSON},
		{Name: "disabled_api_keys", Type: field.TypeJSON, Nullable: true},
		{Name: "supported_models", Type: field.TypeJSON},
		{Name: "manual_models", Type: field.TypeJSON, Nullable: true},
		{Name: "auto_sync_supported_models", Type: field.TypeBool, Default: false},
		{Name: "auto_sync_model_pattern", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "default_test_model", Type: field.TypeString},
		{Name: "policies", Type: field.TypeJSON, Nullable: true},
		{Name: "settings", Type: field.TypeJSON, Nullable: true},
		{Name: "ordering_weight", Type: field.TypeInt, Default: 0},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "remark", Type: field.TypeString, Nullable: true},
	}
	// ChannelsTable holds the schema information for the "channels" table.
	ChannelsTable = &schema.Table{
		Name:       "channels",
		Columns:    ChannelsColumns,
		PrimaryKey: []*schema.Column{ChannelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "channels_by_name",
				Unique:  true,
				Columns: []*schema.Column{ChannelsColumns[6], ChannelsColumns[3]},
			},
		},
	}
	// ChannelModelPricesColumns holds the columns for the "channel_model_prices" table.
	ChannelModelPricesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "model_id", Type: field.TypeString},
		{Name: "price", Type: field.TypeJSON},
		{Name: "reference_id", Type: field.TypeString, Unique: true},
		{Name: "channel_id", Type: field.TypeInt},
	}
	// ChannelModelPricesTable holds the schema information for the "channel_model_prices" table.
	ChannelModelPricesTable = &schema.Table{
		Name:       "channel_model_prices",
		Columns:    ChannelModelPricesColumns,
		PrimaryKey: []*schema.Column{ChannelModelPricesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_model_prices_channels_channel_model_prices",
				Columns:    []*schema.Column{ChannelModelPricesColumns[7]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "channel_model_prices_by_channel_id_model_id",
				Unique:  true,
				Columns: []*schema.Column{ChannelModelPricesColumns[7], ChannelModelPricesColumns[4], ChannelModelPricesColumns[3]},
			},
		},
	}
	// ChannelModelPriceVersionsColumns holds the columns for the "channel_model_price_versions" table.
	ChannelModelPriceVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "channel_id", Type: field.TypeInt},
		{Name: "model_id", Type: field.TypeString},
		{Name: "price", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}},
		{Name: "effective_start_at", Type: field.TypeTime},
		{Name: "effective_end_at", Type: field.TypeTime, Nullable: true},
		{Name: "reference_id", Type: field.TypeString, Unique: true},
		{Name: "channel_model_price_id", Type: field.TypeInt},
	}
	// ChannelModelPriceVersionsTable holds the schema information for the "channel_model_price_versions" table.
	ChannelModelPriceVersionsTable = &schema.Table{
		Name:       "channel_model_price_versions",
		Columns:    ChannelModelPriceVersionsColumns,
		PrimaryKey: []*schema.Column{ChannelModelPriceVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_model_price_versions_channel_model_prices_versions",
				Columns:    []*schema.Column{ChannelModelPriceVersionsColumns[10]},
				RefColumns: []*schema.Column{ChannelModelPricesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ChannelOverrideTemplatesColumns holds the columns for the "channel_override_templates" table.
	ChannelOverrideTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "override_parameters", Type: field.TypeString},
		{Name: "override_headers", Type: field.TypeJSON},
		{Name: "header_override_operations", Type: field.TypeJSON, Nullable: true},
		{Name: "body_override_operations", Type: field.TypeJSON, Nullable: true},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// ChannelOverrideTemplatesTable holds the schema information for the "channel_override_templates" table.
	ChannelOverrideTemplatesTable = &schema.Table{
		Name:       "channel_override_templates",
		Columns:    ChannelOverrideTemplatesColumns,
		PrimaryKey: []*schema.Column{ChannelOverrideTemplatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_override_templates_users_channel_override_templates",
				Columns:    []*schema.Column{ChannelOverrideTemplatesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "channel_override_templates_by_user_name",
				Unique:  true,
				Columns: []*schema.Column{ChannelOverrideTemplatesColumns[10], ChannelOverrideTemplatesColumns[4], ChannelOverrideTemplatesColumns[3]},
			},
		},
	}
	// ChannelProbesColumns holds the columns for the "channel_probes" table.
	ChannelProbesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "total_request_count", Type: field.TypeInt},
		{Name: "success_request_count", Type: field.TypeInt},
		{Name: "avg_tokens_per_second", Type: field.TypeFloat64, Nullable: true},
		{Name: "avg_time_to_first_token_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "timestamp", Type: field.TypeInt64},
		{Name: "channel_id", Type: field.TypeInt},
	}
	// ChannelProbesTable holds the schema information for the "channel_probes" table.
	ChannelProbesTable = &schema.Table{
		Name:       "channel_probes",
		Columns:    ChannelProbesColumns,
		PrimaryKey: []*schema.Column{ChannelProbesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_probes_channels_channel_probes",
				Columns:    []*schema.Column{ChannelProbesColumns[6]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "channel_probes_by_channel_id_timestamp",
				Unique:  false,
				Columns: []*schema.Column{ChannelProbesColumns[6], ChannelProbesColumns[5]},
			},
		},
	}
	// DataStoragesColumns holds the columns for the "data_storages" table.
	DataStoragesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "primary", Type: field.TypeBool, Default: false},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"database", "fs", "s3", "gcs", "webdav"}},
		{Name: "settings", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}, Default: "active"},
	}
	// DataStoragesTable holds the schema information for the "data_storages" table.
	DataStoragesTable = &schema.Table{
		Name:       "data_storages",
		Columns:    DataStoragesColumns,
		PrimaryKey: []*schema.Column{DataStoragesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "data_sources_by_name",
				Unique:  true,
				Columns: []*schema.Column{DataStoragesColumns[4]},
			},
		},
	}
	// ModelsColumns holds the columns for the "models" table.
	ModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "developer", Type: field.TypeString},
		{Name: "model_id", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"chat", "embedding", "rerank", "image_generation", "video_generation"}, Default: "chat"},
		{Name: "name", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString},
		{Name: "group", Type: field.TypeString},
		{Name: "model_card", Type: field.TypeJSON},
		{Name: "settings", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "disabled"},
		{Name: "remark", Type: field.TypeString, Nullable: true},
	}
	// ModelsTable holds the schema information for the "models" table.
	ModelsTable = &schema.Table{
		Name:       "models",
		Columns:    ModelsColumns,
		PrimaryKey: []*schema.Column{ModelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "models_by_name",
				Unique:  true,
				Columns: []*schema.Column{ModelsColumns[7], ModelsColumns[3]},
			},
			{
				Name:    "models_by_model_id",
				Unique:  true,
				Columns: []*schema.Column{ModelsColumns[5], ModelsColumns[3]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}, Default: "active"},
		{Name: "profiles", Type: field.TypeJSON, Nullable: true},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "projects_by_name",
				Unique:  true,
				Columns: []*schema.Column{ProjectsColumns[4], ProjectsColumns[3]},
			},
		},
	}
	// PromptsColumns holds the columns for the "prompts" table.
	PromptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "project_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "role", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled"}, Default: "disabled"},
		{Name: "order", Type: field.TypeInt, Default: 0},
		{Name: "settings", Type: field.TypeJSON},
	}
	// PromptsTable holds the schema information for the "prompts" table.
	PromptsTable = &schema.Table{
		Name:       "prompts",
		Columns:    PromptsColumns,
		PrimaryKey: []*schema.Column{PromptsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "prompts_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{PromptsColumns[4]},
			},
			{
				Name:    "prompts_by_project_id_name",
				Unique:  true,
				Columns: []*schema.Column{PromptsColumns[4], PromptsColumns[5], PromptsColumns[3]},
			},
		},
	}
	// PromptProtectionRulesColumns holds the columns for the "prompt_protection_rules" table.
	PromptProtectionRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "pattern", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "disabled"},
		{Name: "settings", Type: field.TypeJSON},
	}
	// PromptProtectionRulesTable holds the schema information for the "prompt_protection_rules" table.
	PromptProtectionRulesTable = &schema.Table{
		Name:       "prompt_protection_rules",
		Columns:    PromptProtectionRulesColumns,
		PrimaryKey: []*schema.Column{PromptProtectionRulesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "prompt_protection_rules_by_name",
				Unique:  true,
				Columns: []*schema.Column{PromptProtectionRulesColumns[4], PromptProtectionRulesColumns[3]},
			},
		},
	}
	// ProviderQuotaStatusColumns holds the columns for the "provider_quota_status" table.
	ProviderQuotaStatusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "provider_type", Type: field.TypeEnum, Enums: []string{"claudecode", "codex"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"available", "warning", "exhausted", "unknown"}},
		{Name: "quota_data", Type: field.TypeJSON},
		{Name: "next_reset_at", Type: field.TypeTime, Nullable: true},
		{Name: "ready", Type: field.TypeBool, Default: true},
		{Name: "next_check_at", Type: field.TypeTime},
		{Name: "channel_id", Type: field.TypeInt, Unique: true},
	}
	// ProviderQuotaStatusTable holds the schema information for the "provider_quota_status" table.
	ProviderQuotaStatusTable = &schema.Table{
		Name:       "provider_quota_status",
		Columns:    ProviderQuotaStatusColumns,
		PrimaryKey: []*schema.Column{ProviderQuotaStatusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "provider_quota_status_channels_provider_quota_status",
				Columns:    []*schema.Column{ProviderQuotaStatusColumns[10]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "providerquotastatus_channel_id",
				Unique:  true,
				Columns: []*schema.Column{ProviderQuotaStatusColumns[10]},
			},
			{
				Name:    "providerquotastatus_next_check_at",
				Unique:  false,
				Columns: []*schema.Column{ProviderQuotaStatusColumns[9]},
			},
		},
	}
	// RelayDailyUsageSummariesColumns holds the columns for the "relay_daily_usage_summaries" table.
	RelayDailyUsageSummariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "project_id", Type: field.TypeInt},
		{Name: "stat_date", Type: field.TypeTime},
		{Name: "request_count", Type: field.TypeInt64, Default: 0},
		{Name: "total_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "total_charge", Type: field.TypeString, Default: "0"},
		{Name: "total_upstream_cost", Type: field.TypeString, Default: "0"},
		{Name: "last_request_id", Type: field.TypeInt, Nullable: true},
		{Name: "relay_key_id", Type: field.TypeInt},
	}
	// RelayDailyUsageSummariesTable holds the schema information for the "relay_daily_usage_summaries" table.
	RelayDailyUsageSummariesTable = &schema.Table{
		Name:       "relay_daily_usage_summaries",
		Columns:    RelayDailyUsageSummariesColumns,
		PrimaryKey: []*schema.Column{RelayDailyUsageSummariesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relay_daily_usage_summaries_relay_keys_daily_usage_summaries",
				Columns:    []*schema.Column{RelayDailyUsageSummariesColumns[10]},
				RefColumns: []*schema.Column{RelayKeysColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relay_daily_usage_summaries_by_relay_key_stat_date",
				Unique:  true,
				Columns: []*schema.Column{RelayDailyUsageSummariesColumns[10], RelayDailyUsageSummariesColumns[4]},
			},
			{
				Name:    "relay_daily_usage_summaries_by_project_stat_date",
				Unique:  false,
				Columns: []*schema.Column{RelayDailyUsageSummariesColumns[3], RelayDailyUsageSummariesColumns[4]},
			},
			{
				Name:    "relay_daily_usage_summaries_by_stat_date_total_charge",
				Unique:  false,
				Columns: []*schema.Column{RelayDailyUsageSummariesColumns[4], RelayDailyUsageSummariesColumns[7]},
			},
		},
	}
	// RelayKeysColumns holds the columns for the "relay_keys" table.
	RelayKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "display_name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "suspended", "exhausted", "archived"}, Default: "active"},
		{Name: "balance_mode", Type: field.TypeEnum, Enums: []string{"prepaid", "quota_only"}, Default: "prepaid"},
		{Name: "daily_request_limit", Type: field.TypeInt64, Nullable: true},
		{Name: "daily_token_limit", Type: field.TypeInt64, Nullable: true},
		{Name: "monthly_cost_limit", Type: field.TypeString, Nullable: true},
		{Name: "concurrency_limit", Type: field.TypeInt64, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "api_key_id", Type: field.TypeInt, Unique: true},
		{Name: "project_id", Type: field.TypeInt},
		{Name: "product_id", Type: field.TypeInt},
		{Name: "owner_user_id", Type: field.TypeInt, Nullable: true},
	}
	// RelayKeysTable holds the schema information for the "relay_keys" table.
	RelayKeysTable = &schema.Table{
		Name:       "relay_keys",
		Columns:    RelayKeysColumns,
		PrimaryKey: []*schema.Column{RelayKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relay_keys_api_keys_relay_key",
				Columns:    []*schema.Column{RelayKeysColumns[13]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "relay_keys_projects_relay_keys",
				Columns:    []*schema.Column{RelayKeysColumns[14]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "relay_keys_relay_products_relay_keys",
				Columns:    []*schema.Column{RelayKeysColumns[15]},
				RefColumns: []*schema.Column{RelayProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "relay_keys_users_relay_keys",
				Columns:    []*schema.Column{RelayKeysColumns[16]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relay_keys_by_api_key_id",
				Unique:  true,
				Columns: []*schema.Column{RelayKeysColumns[13]},
			},
			{
				Name:    "relay_keys_by_project_status",
				Unique:  false,
				Columns: []*schema.Column{RelayKeysColumns[14], RelayKeysColumns[5]},
			},
			{
				Name:    "relay_keys_by_product_status",
				Unique:  false,
				Columns: []*schema.Column{RelayKeysColumns[15], RelayKeysColumns[5]},
			},
			{
				Name:    "relay_keys_by_expires_at",
				Unique:  false,
				Columns: []*schema.Column{RelayKeysColumns[11]},
			},
		},
	}
	// RelayProductsColumns holds the columns for the "relay_products" table.
	RelayProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "code", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "provider_type", Type: field.TypeEnum, Enums: []string{"claudecode", "codex", "openai_compatible"}},
		{Name: "access_mode", Type: field.TypeEnum, Enums: []string{"shared_capacity"}, Default: "shared_capacity"},
		{Name: "billing_mode", Type: field.TypeEnum, Enums: []string{"prepaid", "quota_only"}, Default: "prepaid"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "active", "archived"}, Default: "draft"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "list_price_config", Type: field.TypeJSON, Nullable: true},
		{Name: "allowed_models", Type: field.TypeJSON, Nullable: true},
		{Name: "request_timeout_seconds", Type: field.TypeInt, Default: 600},
	}
	// RelayProductsTable holds the schema information for the "relay_products" table.
	RelayProductsTable = &schema.Table{
		Name:       "relay_products",
		Columns:    RelayProductsColumns,
		PrimaryKey: []*schema.Column{RelayProductsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "relay_products_by_code",
				Unique:  true,
				Columns: []*schema.Column{RelayProductsColumns[4], RelayProductsColumns[3]},
			},
			{
				Name:    "relay_products_by_status",
				Unique:  false,
				Columns: []*schema.Column{RelayProductsColumns[9]},
			},
			{
				Name:    "relay_products_by_provider_type",
				Unique:  false,
				Columns: []*schema.Column{RelayProductsColumns[6]},
			},
		},
	}
	// RelayProductChannelsColumns holds the columns for the "relay_product_channels" table.
	RelayProductChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "weight", Type: field.TypeInt, Default: 100},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "paused"}, Default: "active"},
		{Name: "allow_fallback", Type: field.TypeBool, Default: true},
		{Name: "model_filter", Type: field.TypeJSON, Nullable: true},
		{Name: "max_inflight", Type: field.TypeInt, Nullable: true},
		{Name: "channel_id", Type: field.TypeInt},
		{Name: "product_id", Type: field.TypeInt},
	}
	// RelayProductChannelsTable holds the schema information for the "relay_product_channels" table.
	RelayProductChannelsTable = &schema.Table{
		Name:       "relay_product_channels",
		Columns:    RelayProductChannelsColumns,
		PrimaryKey: []*schema.Column{RelayProductChannelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relay_product_channels_channels_relay_product_bindings",
				Columns:    []*schema.Column{RelayProductChannelsColumns[9]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "relay_product_channels_relay_products_channel_bindings",
				Columns:    []*schema.Column{RelayProductChannelsColumns[10]},
				RefColumns: []*schema.Column{RelayProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relay_product_channels_by_product_channel",
				Unique:  true,
				Columns: []*schema.Column{RelayProductChannelsColumns[10], RelayProductChannelsColumns[9]},
			},
			{
				Name:    "relay_product_channels_by_product_status_priority",
				Unique:  false,
				Columns: []*schema.Column{RelayProductChannelsColumns[10], RelayProductChannelsColumns[5], RelayProductChannelsColumns[3]},
			},
		},
	}
	// RelayWalletsColumns holds the columns for the "relay_wallets" table.
	RelayWalletsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "project_id", Type: field.TypeInt},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "available_amount", Type: field.TypeString, Default: "0"},
		{Name: "frozen_amount", Type: field.TypeString, Default: "0"},
		{Name: "overdraft_limit", Type: field.TypeString, Default: "0"},
		{Name: "version", Type: field.TypeInt64, Default: 1},
		{Name: "relay_key_id", Type: field.TypeInt, Unique: true},
	}
	// RelayWalletsTable holds the schema information for the "relay_wallets" table.
	RelayWalletsTable = &schema.Table{
		Name:       "relay_wallets",
		Columns:    RelayWalletsColumns,
		PrimaryKey: []*schema.Column{RelayWalletsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relay_wallets_relay_keys_wallet",
				Columns:    []*schema.Column{RelayWalletsColumns[9]},
				RefColumns: []*schema.Column{RelayKeysColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relay_wallets_by_relay_key_id",
				Unique:  true,
				Columns: []*schema.Column{RelayWalletsColumns[9]},
			},
			{
				Name:    "relay_wallets_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{RelayWalletsColumns[3]},
			},
		},
	}
	// RelayWalletLedgerEntriesColumns holds the columns for the "relay_wallet_ledger_entries" table.
	RelayWalletLedgerEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "project_id", Type: field.TypeInt},
		{Name: "request_id", Type: field.TypeInt, Nullable: true},
		{Name: "usage_log_id", Type: field.TypeInt, Nullable: true},
		{Name: "direction", Type: field.TypeEnum, Enums: []string{"credit", "debit"}},
		{Name: "scene", Type: field.TypeEnum, Enums: []string{"recharge", "consume", "refund", "freeze", "unfreeze", "manual_adjust"}},
		{Name: "amount", Type: field.TypeString},
		{Name: "balance_before", Type: field.TypeString},
		{Name: "balance_after", Type: field.TypeString},
		{Name: "upstream_cost", Type: field.TypeString, Nullable: true},
		{Name: "price_snapshot", Type: field.TypeJSON, Nullable: true},
		{Name: "idempotency_key", Type: field.TypeString},
		{Name: "operator_user_id", Type: field.TypeInt, Nullable: true},
		{Name: "remark", Type: field.TypeString, Nullable: true},
		{Name: "relay_key_id", Type: field.TypeInt},
	}
	// RelayWalletLedgerEntriesTable holds the schema information for the "relay_wallet_ledger_entries" table.
	RelayWalletLedgerEntriesTable = &schema.Table{
		Name:       "relay_wallet_ledger_entries",
		Columns:    RelayWalletLedgerEntriesColumns,
		PrimaryKey: []*schema.Column{RelayWalletLedgerEntriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relay_wallet_ledger_entries_relay_keys_ledger_entries",
				Columns:    []*schema.Column{RelayWalletLedgerEntriesColumns[16]},
				RefColumns: []*schema.Column{RelayKeysColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relay_wallet_ledger_entries_by_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{RelayWalletLedgerEntriesColumns[13]},
			},
			{
				Name:    "relay_wallet_ledger_entries_by_relay_key_created_at",
				Unique:  false,
				Columns: []*schema.Column{RelayWalletLedgerEntriesColumns[16], RelayWalletLedgerEntriesColumns[1]},
			},
			{
				Name:    "relay_wallet_ledger_entries_by_project_created_at",
				Unique:  false,
				Columns: []*schema.Column{RelayWalletLedgerEntriesColumns[3], RelayWalletLedgerEntriesColumns[1]},
			},
			{
				Name:    "relay_wallet_ledger_entries_by_request_id",
				Unique:  false,
				Columns: []*schema.Column{RelayWalletLedgerEntriesColumns[4]},
			},
			{
				Name:    "relay_wallet_ledger_entries_by_usage_log_id",
				Unique:  false,
				Columns: []*schema.Column{RelayWalletLedgerEntriesColumns[5]},
			},
		},
	}
	// RequestsColumns holds the columns for the "requests" table.
	RequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"api", "playground", "test"}, Default: "api"},
		{Name: "model_id", Type: field.TypeString},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "request_headers", Type: field.TypeJSON, Nullable: true},
		{Name: "request_body", Type: field.TypeJSON},
		{Name: "response_body", Type: field.TypeJSON, Nullable: true},
		{Name: "response_chunks", Type: field.TypeJSON, Nullable: true},
		{Name: "external_id", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "processing", "completed", "failed", "canceled"}},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "client_ip", Type: field.TypeString, Default: ""},
		{Name: "metrics_latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "metrics_first_token_latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "metrics_reasoning_duration_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "content_saved", Type: field.TypeBool, Default: false},
		{Name: "content_storage_id", Type: field.TypeInt, Nullable: true},
		{Name: "content_storage_key", Type: field.TypeString, Nullable: true},
		{Name: "content_saved_at", Type: field.TypeTime, Nullable: true},
		{Name: "api_key_id", Type: field.TypeInt, Nullable: true},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "data_storage_id", Type: field.TypeInt, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "trace_id", Type: field.TypeInt, Nullable: true},
	}
	// RequestsTable holds the schema information for the "requests" table.
	RequestsTable = &schema.Table{
		Name:       "requests",
		Columns:    RequestsColumns,
		PrimaryKey: []*schema.Column{RequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "requests_api_keys_requests",
				Columns:    []*schema.Column{RequestsColumns[21]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_channels_requests",
				Columns:    []*schema.Column{RequestsColumns[22]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_data_storages_requests",
				Columns:    []*schema.Column{RequestsColumns[23]},
				RefColumns: []*schema.Column{DataStoragesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_projects_requests",
				Columns:    []*schema.Column{RequestsColumns[24]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "requests_traces_requests",
				Columns:    []*schema.Column{RequestsColumns[25]},
				RefColumns: []*schema.Column{TracesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "requests_by_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[21], RequestsColumns[1]},
			},
			{
				Name:    "requests_by_project_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[24], RequestsColumns[1]},
			},
			{
				Name:    "requests_by_channel_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[22], RequestsColumns[1]},
			},
			{
				Name:    "requests_by_trace_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[25], RequestsColumns[1]},
			},
			{
				Name:    "requests_by_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[1]},
			},
		},
	}
	// RequestExecutionsColumns holds the columns for the "request_executions" table.
	RequestExecutionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "external_id", Type: field.TypeString, Nullable: true},
		{Name: "model_id", Type: field.TypeString},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "request_body", Type: field.TypeJSON},
		{Name: "response_body", Type: field.TypeJSON, Nullable: true},
		{Name: "response_chunks", Type: field.TypeJSON, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "response_status_code", Type: field.TypeInt, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "processing", "completed", "failed", "canceled"}},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "metrics_latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "metrics_first_token_latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "metrics_reasoning_duration_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "request_headers", Type: field.TypeJSON, Nullable: true},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "data_storage_id", Type: field.TypeInt, Nullable: true},
		{Name: "request_id", Type: field.TypeInt},
	}
	// RequestExecutionsTable holds the schema information for the "request_executions" table.
	RequestExecutionsTable = &schema.Table{
		Name:       "request_executions",
		Columns:    RequestExecutionsColumns,
		PrimaryKey: []*schema.Column{RequestExecutionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "request_executions_channels_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[18]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "request_executions_data_storages_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[19]},
				RefColumns: []*schema.Column{DataStoragesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "request_executions_requests_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[20]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "request_executions_by_request_id_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestExecutionsColumns[20], RequestExecutionsColumns[12], RequestExecutionsColumns[1]},
			},
			{
				Name:    "request_executions_by_channel_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestExecutionsColumns[18]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "level", Type: field.TypeEnum, Enums: []string{"system", "project"}, Default: "system"},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Nullable: true},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "roles_projects_roles",
				Columns:    []*schema.Column{RolesColumns[7]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "roles_by_project_id_name",
				Unique:  true,
				Columns: []*schema.Column{RolesColumns[7], RolesColumns[4]},
			},
			{
				Name:    "roles_by_level",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[5]},
			},
		},
	}
	// SystemsColumns holds the columns for the "systems" table.
	SystemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, SchemaType: map[string]string{"mysql": "mediumtext"}},
	}
	// SystemsTable holds the schema information for the "systems" table.
	SystemsTable = &schema.Table{
		Name:       "systems",
		Columns:    SystemsColumns,
		PrimaryKey: []*schema.Column{SystemsColumns[0]},
	}
	// ThreadsColumns holds the columns for the "threads" table.
	ThreadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "thread_id", Type: field.TypeString, Unique: true},
		{Name: "project_id", Type: field.TypeInt},
	}
	// ThreadsTable holds the schema information for the "threads" table.
	ThreadsTable = &schema.Table{
		Name:       "threads",
		Columns:    ThreadsColumns,
		PrimaryKey: []*schema.Column{ThreadsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "threads_projects_threads",
				Columns:    []*schema.Column{ThreadsColumns[4]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "threads_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{ThreadsColumns[4]},
			},
			{
				Name:    "threads_by_thread_id",
				Unique:  true,
				Columns: []*schema.Column{ThreadsColumns[3]},
			},
		},
	}
	// TracesColumns holds the columns for the "traces" table.
	TracesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "trace_id", Type: field.TypeString, Unique: true},
		{Name: "project_id", Type: field.TypeInt},
		{Name: "thread_id", Type: field.TypeInt, Nullable: true},
	}
	// TracesTable holds the schema information for the "traces" table.
	TracesTable = &schema.Table{
		Name:       "traces",
		Columns:    TracesColumns,
		PrimaryKey: []*schema.Column{TracesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "traces_projects_traces",
				Columns:    []*schema.Column{TracesColumns[4]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "traces_threads_traces",
				Columns:    []*schema.Column{TracesColumns[5]},
				RefColumns: []*schema.Column{ThreadsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "traces_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{TracesColumns[4]},
			},
			{
				Name:    "traces_by_trace_id",
				Unique:  true,
				Columns: []*schema.Column{TracesColumns[3]},
			},
			{
				Name:    "traces_by_thread_id",
				Unique:  false,
				Columns: []*schema.Column{TracesColumns[5]},
			},
		},
	}
	// UsageLogsColumns holds the columns for the "usage_logs" table.
	UsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "api_key_id", Type: field.TypeInt, Nullable: true},
		{Name: "model_id", Type: field.TypeString},
		{Name: "prompt_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "completion_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "total_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "prompt_audio_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_cached_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_write_cached_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_write_cached_tokens_5m", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_write_cached_tokens_1h", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_audio_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_reasoning_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_accepted_prediction_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_rejected_prediction_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"api", "playground", "test"}, Default: "api"},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "total_cost", Type: field.TypeFloat64, Nullable: true},
		{Name: "cost_items", Type: field.TypeJSON, Nullable: true},
		{Name: "cost_price_reference_id", Type: field.TypeString, Nullable: true},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "request_id", Type: field.TypeInt},
	}
	// UsageLogsTable holds the schema information for the "usage_logs" table.
	UsageLogsTable = &schema.Table{
		Name:       "usage_logs",
		Columns:    UsageLogsColumns,
		PrimaryKey: []*schema.Column{UsageLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "usage_logs_channels_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[22]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_projects_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[23]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "usage_logs_requests_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[24]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usage_logs_by_request_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[24]},
			},
			{
				Name:    "usage_logs_by_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_model_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[4], UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_project_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[23], UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_channel_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[22], UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[3], UsageLogsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "email", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"activated", "deactivated"}, Default: "activated"},
		{Name: "prefer_language", Type: field.TypeString, Default: "en"},
		{Name: "password", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString, Default: ""},
		{Name: "last_name", Type: field.TypeString, Default: ""},
		{Name: "avatar", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "mediumtext"}},
		{Name: "is_owner", Type: field.TypeBool, Default: false},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[4], UsersColumns[3]},
			},
		},
	}
	// UserPointAccountsColumns holds the columns for the "user_point_accounts" table.
	UserPointAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "available_points", Type: field.TypeString, Default: "0"},
		{Name: "pending_points", Type: field.TypeString, Default: "0"},
		{Name: "frozen_points", Type: field.TypeString, Default: "0"},
		{Name: "lifetime_earned", Type: field.TypeString, Default: "0"},
		{Name: "lifetime_spent", Type: field.TypeString, Default: "0"},
		{Name: "version", Type: field.TypeInt64, Default: 1},
	}
	// UserPointAccountsTable holds the schema information for the "user_point_accounts" table.
	UserPointAccountsTable = &schema.Table{
		Name:       "user_point_accounts",
		Columns:    UserPointAccountsColumns,
		PrimaryKey: []*schema.Column{UserPointAccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_point_accounts_by_user_id",
				Unique:  true,
				Columns: []*schema.Column{UserPointAccountsColumns[3]},
			},
		},
	}
	// UserPointLedgerEntriesColumns holds the columns for the "user_point_ledger_entries" table.
	UserPointLedgerEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "direction", Type: field.TypeEnum, Enums: []string{"credit", "debit"}},
		{Name: "scene", Type: field.TypeEnum, Enums: []string{"contribution_pending", "contribution_reward", "consume", "adjustment"}},
		{Name: "points", Type: field.TypeString},
		{Name: "balance_before", Type: field.TypeString},
		{Name: "balance_after", Type: field.TypeString},
		{Name: "idempotency_key", Type: field.TypeString},
		{Name: "related_channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "related_request_id", Type: field.TypeInt, Nullable: true},
		{Name: "related_usage_log_id", Type: field.TypeInt, Nullable: true},
		{Name: "related_api_key_id", Type: field.TypeInt, Nullable: true},
		{Name: "related_project_id", Type: field.TypeInt, Nullable: true},
		{Name: "conversion_rate_snapshot", Type: field.TypeString, Nullable: true},
		{Name: "settlement_status", Type: field.TypeEnum, Enums: []string{"posted"}, Default: "posted"},
		{Name: "remark", Type: field.TypeString, Nullable: true},
	}
	// UserPointLedgerEntriesTable holds the schema information for the "user_point_ledger_entries" table.
	UserPointLedgerEntriesTable = &schema.Table{
		Name:       "user_point_ledger_entries",
		Columns:    UserPointLedgerEntriesColumns,
		PrimaryKey: []*schema.Column{UserPointLedgerEntriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_point_ledger_entries_by_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{UserPointLedgerEntriesColumns[9]},
			},
			{
				Name:    "user_point_ledger_entries_by_user_created_at",
				Unique:  false,
				Columns: []*schema.Column{UserPointLedgerEntriesColumns[3], UserPointLedgerEntriesColumns[1]},
			},
			{
				Name:    "user_point_ledger_entries_by_request_id",
				Unique:  false,
				Columns: []*schema.Column{UserPointLedgerEntriesColumns[11]},
			},
			{
				Name:    "user_point_ledger_entries_by_usage_log_id",
				Unique:  false,
				Columns: []*schema.Column{UserPointLedgerEntriesColumns[12]},
			},
			{
				Name:    "user_point_ledger_entries_by_channel_id",
				Unique:  false,
				Columns: []*schema.Column{UserPointLedgerEntriesColumns[10]},
			},
		},
	}
	// UserProjectsColumns holds the columns for the "user_projects" table.
	UserProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "is_owner", Type: field.TypeBool, Default: false},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "project_id", Type: field.TypeInt},
	}
	// UserProjectsTable holds the schema information for the "user_projects" table.
	UserProjectsTable = &schema.Table{
		Name:       "user_projects",
		Columns:    UserProjectsColumns,
		PrimaryKey: []*schema.Column{UserProjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_projects_users_user",
				Columns:    []*schema.Column{UserProjectsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_projects_projects_project",
				Columns:    []*schema.Column{UserProjectsColumns[6]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_projects_by_user_id_project_id",
				Unique:  true,
				Columns: []*schema.Column{UserProjectsColumns[5], UserProjectsColumns[6]},
			},
			{
				Name:    "user_projects_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{UserProjectsColumns[6]},
			},
		},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Default: schema.Expr("CURRENT_TIMESTAMP")},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "role_id", Type: field.TypeInt},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_roles_users_user",
				Columns:    []*schema.Column{UserRolesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_roles_roles_role",
				Columns:    []*schema.Column{UserRolesColumns[4]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_roles_by_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{UserRolesColumns[3], UserRolesColumns[4]},
			},
			{
				Name:    "user_roles_by_role_id",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[4]},
			},
		},
	}
	// ProjectPromptsColumns holds the columns for the "project_prompts" table.
	ProjectPromptsColumns = []*schema.Column{
		{Name: "project_id", Type: field.TypeInt},
		{Name: "prompt_id", Type: field.TypeInt},
	}
	// ProjectPromptsTable holds the schema information for the "project_prompts" table.
	ProjectPromptsTable = &schema.Table{
		Name:       "project_prompts",
		Columns:    ProjectPromptsColumns,
		PrimaryKey: []*schema.Column{ProjectPromptsColumns[0], ProjectPromptsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_prompts_project_id",
				Columns:    []*schema.Column{ProjectPromptsColumns[0]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "project_prompts_prompt_id",
				Columns:    []*schema.Column{ProjectPromptsColumns[1]},
				RefColumns: []*schema.Column{PromptsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		ChannelsTable,
		ChannelModelPricesTable,
		ChannelModelPriceVersionsTable,
		ChannelOverrideTemplatesTable,
		ChannelProbesTable,
		DataStoragesTable,
		ModelsTable,
		ProjectsTable,
		PromptsTable,
		PromptProtectionRulesTable,
		ProviderQuotaStatusTable,
		RelayDailyUsageSummariesTable,
		RelayKeysTable,
		RelayProductsTable,
		RelayProductChannelsTable,
		RelayWalletsTable,
		RelayWalletLedgerEntriesTable,
		RequestsTable,
		RequestExecutionsTable,
		RolesTable,
		SystemsTable,
		ThreadsTable,
		TracesTable,
		UsageLogsTable,
		UsersTable,
		UserPointAccountsTable,
		UserPointLedgerEntriesTable,
		UserProjectsTable,
		UserRolesTable,
		ProjectPromptsTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = ProjectsTable
	APIKeysTable.ForeignKeys[1].RefTable = UsersTable
	ChannelModelPricesTable.ForeignKeys[0].RefTable = ChannelsTable
	ChannelModelPriceVersionsTable.ForeignKeys[0].RefTable = ChannelModelPricesTable
	ChannelOverrideTemplatesTable.ForeignKeys[0].RefTable = UsersTable
	ChannelProbesTable.ForeignKeys[0].RefTable = ChannelsTable
	ProviderQuotaStatusTable.ForeignKeys[0].RefTable = ChannelsTable
	RelayDailyUsageSummariesTable.ForeignKeys[0].RefTable = RelayKeysTable
	RelayKeysTable.ForeignKeys[0].RefTable = APIKeysTable
	RelayKeysTable.ForeignKeys[1].RefTable = ProjectsTable
	RelayKeysTable.ForeignKeys[2].RefTable = RelayProductsTable
	RelayKeysTable.ForeignKeys[3].RefTable = UsersTable
	RelayProductChannelsTable.ForeignKeys[0].RefTable = ChannelsTable
	RelayProductChannelsTable.ForeignKeys[1].RefTable = RelayProductsTable
	RelayWalletsTable.ForeignKeys[0].RefTable = RelayKeysTable
	RelayWalletLedgerEntriesTable.ForeignKeys[0].RefTable = RelayKeysTable
	RequestsTable.ForeignKeys[0].RefTable = APIKeysTable
	RequestsTable.ForeignKeys[1].RefTable = ChannelsTable
	RequestsTable.ForeignKeys[2].RefTable = DataStoragesTable
	RequestsTable.ForeignKeys[3].RefTable = ProjectsTable
	RequestsTable.ForeignKeys[4].RefTable = TracesTable
	RequestExecutionsTable.ForeignKeys[0].RefTable = ChannelsTable
	RequestExecutionsTable.ForeignKeys[1].RefTable = DataStoragesTable
	RequestExecutionsTable.ForeignKeys[2].RefTable = RequestsTable
	RolesTable.ForeignKeys[0].RefTable = ProjectsTable
	ThreadsTable.ForeignKeys[0].RefTable = ProjectsTable
	TracesTable.ForeignKeys[0].RefTable = ProjectsTable
	TracesTable.ForeignKeys[1].RefTable = ThreadsTable
	UsageLogsTable.ForeignKeys[0].RefTable = ChannelsTable
	UsageLogsTable.ForeignKeys[1].RefTable = ProjectsTable
	UsageLogsTable.ForeignKeys[2].RefTable = RequestsTable
	UserProjectsTable.ForeignKeys[0].RefTable = UsersTable
	UserProjectsTable.ForeignKeys[1].RefTable = ProjectsTable
	UserRolesTable.ForeignKeys[0].RefTable = UsersTable
	UserRolesTable.ForeignKeys[1].RefTable = RolesTable
	ProjectPromptsTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectPromptsTable.ForeignKeys[1].RefTable = PromptsTable
}
