// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/relaydailyusagesummary"
	"github.com/looplj/axonhub/internal/ent/relaykey"
)

// RelayDailyUsageSummaryCreate is the builder for creating a RelayDailyUsageSummary entity.
type RelayDailyUsageSummaryCreate struct {
	config
	mutation *RelayDailyUsageSummaryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RelayDailyUsageSummaryCreate) SetCreatedAt(v time.Time) *RelayDailyUsageSummaryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RelayDailyUsageSummaryCreate) SetNillableCreatedAt(v *time.Time) *RelayDailyUsageSummaryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RelayDailyUsageSummaryCreate) SetUpdatedAt(v time.Time) *RelayDailyUsageSummaryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RelayDailyUsageSummaryCreate) SetNillableUpdatedAt(v *time.Time) *RelayDailyUsageSummaryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRelayKeyID sets the "relay_key_id" field.
func (_c *RelayDailyUsageSummaryCreate) SetRelayKeyID(v int) *RelayDailyUsageSummaryCreate {
	_c.mutation.SetRelayKeyID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *RelayDailyUsageSummaryCreate) SetProjectID(v int) *RelayDailyUsageSummaryCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetStatDate sets the "stat_date" field.
func (_c *RelayDailyUsageSummaryCreate) SetStatDate(v time.Time) *RelayDailyUsageSummaryCreate {
	_c.mutation.SetStatDate(v)
	return _c
}

// SetRequestCount sets the "request_count" field.
func (_c *RelayDailyUsageSummaryCreate) SetRequestCount(v int64) *RelayDailyUsageSummaryCreate {
	_c.mutation.SetRequestCount(v)
	return _c
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_c *RelayDailyUsageSummaryCreate) SetNillableRequestCount(v *int64) *RelayDailyUsageSummaryCreate {
	if v != nil {
		_c.SetRequestCount(*v)
	}
	return _c
}

// SetTotalTokens sets the "total_tokens" field.
func (_c *RelayDailyUsageSummaryCreate) SetTotalTokens(v int64) *RelayDailyUsageSummaryCreate {
	_c.mutation.SetTotalTokens(v)
	return _c
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_c *RelayDailyUsageSummaryCreate) SetNillableTotalTokens(v *int64) *RelayDailyUsageSummaryCreate {
	if v != nil {
		_c.SetTotalTokens(*v)
	}
	return _c
}

// SetTotalCharge sets the "total_charge" field.
func (_c *RelayDailyUsageSummaryCreate) SetTotalCharge(v string) *RelayDailyUsageSummaryCreate {
	_c.mutation.SetTotalCharge(v)
	return _c
}

// SetNillableTotalCharge sets the "total_charge" field if the given value is not nil.
func (_c *RelayDailyUsageSummaryCreate) SetNillableTotalCharge(v *string) *RelayDailyUsageSummaryCreate {
	if v != nil {
		_c.SetTotalCharge(*v)
	}
	return _c
}

// SetTotalUpstreamCost sets the "total_upstream_cost" field.
func (_c *RelayDailyUsageSummaryCreate) SetTotalUpstreamCost(v string) *RelayDailyUsageSummaryCreate {
	_c.mutation.SetTotalUpstreamCost(v)
	return _c
}

// SetNillableTotalUpstreamCost sets the "total_upstream_cost" field if the given value is not nil.
func (_c *RelayDailyUsageSummaryCreate) SetNillableTotalUpstreamCost(v *string) *RelayDailyUsageSummaryCreate {
	if v != nil {
		_c.SetTotalUpstreamCost(*v)
	}
	return _c
}

// SetLastRequestID sets the "last_request_id" field.
func (_c *RelayDailyUsageSummaryCreate) SetLastRequestID(v int) *RelayDailyUsageSummaryCreate {
	_c.mutation.SetLastRequestID(v)
	return _c
}

// SetNillableLastRequestID sets the "last_request_id" field if the given value is not nil.
func (_c *RelayDailyUsageSummaryCreate) SetNillableLastRequestID(v *int) *RelayDailyUsageSummaryCreate {
	if v != nil {
		_c.SetLastRequestID(*v)
	}
	return _c
}

// SetRelayKey sets the "relay_key" edge to the RelayKey entity.
func (_c *RelayDailyUsageSummaryCreate) SetRelayKey(v *RelayKey) *RelayDailyUsageSummaryCreate {
	return _c.SetRelayKeyID(v.ID)
}

// Mutation returns the RelayDailyUsageSummaryMutation object of the builder.
func (_c *RelayDailyUsageSummaryCreate) Mutation() *RelayDailyUsageSummaryMutation {
	return _c.mutation
}

// Save creates the RelayDailyUsageSummary in the database.
func (_c *RelayDailyUsageSummaryCreate) Save(ctx context.Context) (*RelayDailyUsageSummary, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RelayDailyUsageSummaryCreate) SaveX(ctx context.Context) *RelayDailyUsageSummary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelayDailyUsageSummaryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelayDailyUsageSummaryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RelayDailyUsageSummaryCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if relaydailyusagesummary.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaydailyusagesummary.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := relaydailyusagesummary.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if relaydailyusagesummary.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaydailyusagesummary.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := relaydailyusagesummary.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RequestCount(); !ok {
		v := relaydailyusagesummary.DefaultRequestCount
		_c.mutation.SetRequestCount(v)
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		v := relaydailyusagesummary.DefaultTotalTokens
		_c.mutation.SetTotalTokens(v)
	}
	if _, ok := _c.mutation.TotalCharge(); !ok {
		v := relaydailyusagesummary.DefaultTotalCharge
		_c.mutation.SetTotalCharge(v)
	}
	if _, ok := _c.mutation.TotalUpstreamCost(); !ok {
		v := relaydailyusagesummary.DefaultTotalUpstreamCost
		_c.mutation.SetTotalUpstreamCost(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RelayDailyUsageSummaryCreate) check() error {
	if _, ok := _c.mutation.RelayKeyID(); !ok {
		return &ValidationError{Name: "relay_key_id", err: errors.New(`ent: missing required field "RelayDailyUsageSummary.relay_key_id"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "RelayDailyUsageSummary.project_id"`)}
	}
	if _, ok := _c.mutation.StatDate(); !ok {
		return &ValidationError{Name: "stat_date", err: errors.New(`ent: missing required field "RelayDailyUsageSummary.stat_date"`)}
	}
	if _, ok := _c.mutation.RequestCount(); !ok {
		return &ValidationError{Name: "request_count", err: errors.New(`ent: missing required field "RelayDailyUsageSummary.request_count"`)}
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		return &ValidationError{Name: "total_tokens", err: errors.New(`ent: missing required field "RelayDailyUsageSummary.total_tokens"`)}
	}
	if _, ok := _c.mutation.TotalCharge(); !ok {
		return &ValidationError{Name: "total_charge", err: errors.New(`ent: missing required field "RelayDailyUsageSummary.total_charge"`)}
	}
	if _, ok := _c.mutation.TotalUpstreamCost(); !ok {
		return &ValidationError{Name: "total_upstream_cost", err: errors.New(`ent: missing required field "RelayDailyUsageSummary.total_upstream_cost"`)}
	}
	if len(_c.mutation.RelayKeyIDs()) == 0 {
		return &ValidationError{Name: "relay_key", err: errors.New(`ent: missing required edge "RelayDailyUsageSummary.relay_key"`)}
	}
	return nil
}

func (_c *RelayDailyUsageSummaryCreate) sqlSave(ctx context.Context) (*RelayDailyUsageSummary, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RelayDailyUsageSummaryCreate) createSpec() (*RelayDailyUsageSummary, *sqlgraph.CreateSpec) {
	var (
		_node = &RelayDailyUsageSummary{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(relaydailyusagesummary.Table, sqlgraph.NewFieldSpec(relaydailyusagesummary.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(relaydailyusagesummary.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(relaydailyusagesummary.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(relaydailyusagesummary.FieldProjectID, field.TypeInt, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.StatDate(); ok {
		_spec.SetField(relaydailyusagesummary.FieldStatDate, field.TypeTime, value)
		_node.StatDate = value
	}
	if value, ok := _c.mutation.RequestCount(); ok {
		_spec.SetField(relaydailyusagesummary.FieldRequestCount, field.TypeInt64, value)
		_node.RequestCount = value
	}
	if value, ok := _c.mutation.TotalTokens(); ok {
		_spec.SetField(relaydailyusagesummary.FieldTotalTokens, field.TypeInt64, value)
		_node.TotalTokens = value
	}
	if value, ok := _c.mutation.TotalCharge(); ok {
		_spec.SetField(relaydailyusagesummary.FieldTotalCharge, field.TypeString, value)
		_node.TotalCharge = value
	}
	if value, ok := _c.mutation.TotalUpstreamCost(); ok {
		_spec.SetField(relaydailyusagesummary.FieldTotalUpstreamCost, field.TypeString, value)
		_node.TotalUpstreamCost = value
	}
	if value, ok := _c.mutation.LastRequestID(); ok {
		_spec.SetField(relaydailyusagesummary.FieldLastRequestID, field.TypeInt, value)
		_node.LastRequestID = &value
	}
	if nodes := _c.mutation.RelayKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relaydailyusagesummary.RelayKeyTable,
			Columns: []string{relaydailyusagesummary.RelayKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaykey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RelayKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelayDailyUsageSummary.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelayDailyUsageSummaryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RelayDailyUsageSummaryCreate) OnConflict(opts ...sql.ConflictOption) *RelayDailyUsageSummaryUpsertOne {
	_c.conflict = opts
	return &RelayDailyUsageSummaryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelayDailyUsageSummary.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelayDailyUsageSummaryCreate) OnConflictColumns(columns ...string) *RelayDailyUsageSummaryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelayDailyUsageSummaryUpsertOne{
		create: _c,
	}
}

type (
	// RelayDailyUsageSummaryUpsertOne is the builder for "upsert"-ing
	//  one RelayDailyUsageSummary node.
	RelayDailyUsageSummaryUpsertOne struct {
		create *RelayDailyUsageSummaryCreate
	}

	// RelayDailyUsageSummaryUpsert is the "OnConflict" setter.
	RelayDailyUsageSummaryUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RelayDailyUsageSummaryUpsert) SetUpdatedAt(v time.Time) *RelayDailyUsageSummaryUpsert {
	u.Set(relaydailyusagesummary.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsert) UpdateUpdatedAt() *RelayDailyUsageSummaryUpsert {
	u.SetExcluded(relaydailyusagesummary.FieldUpdatedAt)
	return u
}

// SetRequestCount sets the "request_count" field.
func (u *RelayDailyUsageSummaryUpsert) SetRequestCount(v int64) *RelayDailyUsageSummaryUpsert {
	u.Set(relaydailyusagesummary.FieldRequestCount, v)
	return u
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsert) UpdateRequestCount() *RelayDailyUsageSummaryUpsert {
	u.SetExcluded(relaydailyusagesummary.FieldRequestCount)
	return u
}

// AddRequestCount adds v to the "request_count" field.
func (u *RelayDailyUsageSummaryUpsert) AddRequestCount(v int64) *RelayDailyUsageSummaryUpsert {
	u.Add(relaydailyusagesummary.FieldRequestCount, v)
	return u
}

// SetTotalTokens sets the "total_tokens" field.
func (u *RelayDailyUsageSummaryUpsert) SetTotalTokens(v int64) *RelayDailyUsageSummaryUpsert {
	u.Set(relaydailyusagesummary.FieldTotalTokens, v)
	return u
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsert) UpdateTotalTokens() *RelayDailyUsageSummaryUpsert {
	u.SetExcluded(relaydailyusagesummary.FieldTotalTokens)
	return u
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *RelayDailyUsageSummaryUpsert) AddTotalTokens(v int64) *RelayDailyUsageSummaryUpsert {
	u.Add(relaydailyusagesummary.FieldTotalTokens, v)
	return u
}

// SetTotalCharge sets the "total_charge" field.
func (u *RelayDailyUsageSummaryUpsert) SetTotalCharge(v string) *RelayDailyUsageSummaryUpsert {
	u.Set(relaydailyusagesummary.FieldTotalCharge, v)
	return u
}

// UpdateTotalCharge sets the "total_charge" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsert) UpdateTotalCharge() *RelayDailyUsageSummaryUpsert {
	u.SetExcluded(relaydailyusagesummary.FieldTotalCharge)
	return u
}

// SetTotalUpstreamCost sets the "total_upstream_cost" field.
func (u *RelayDailyUsageSummaryUpsert) SetTotalUpstreamCost(v string) *RelayDailyUsageSummaryUpsert {
	u.Set(relaydailyusagesummary.FieldTotalUpstreamCost, v)
	return u
}

// UpdateTotalUpstreamCost sets the "total_upstream_cost" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsert) UpdateTotalUpstreamCost() *RelayDailyUsageSummaryUpsert {
	u.SetExcluded(relaydailyusagesummary.FieldTotalUpstreamCost)
	return u
}

// SetLastRequestID sets the "last_request_id" field.
func (u *RelayDailyUsageSummaryUpsert) SetLastRequestID(v int) *RelayDailyUsageSummaryUpsert {
	u.Set(relaydailyusagesummary.FieldLastRequestID, v)
	return u
}

// UpdateLastRequestID sets the "last_request_id" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsert) UpdateLastRequestID() *RelayDailyUsageSummaryUpsert {
	u.SetExcluded(relaydailyusagesummary.FieldLastRequestID)
	return u
}

// AddLastRequestID adds v to the "last_request_id" field.
func (u *RelayDailyUsageSummaryUpsert) AddLastRequestID(v int) *RelayDailyUsageSummaryUpsert {
	u.Add(relaydailyusagesummary.FieldLastRequestID, v)
	return u
}

// ClearLastRequestID clears the value of the "last_request_id" field.
func (u *RelayDailyUsageSummaryUpsert) ClearLastRequestID() *RelayDailyUsageSummaryUpsert {
	u.SetNull(relaydailyusagesummary.FieldLastRequestID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RelayDailyUsageSummary.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelayDailyUsageSummaryUpsertOne) UpdateNewValues() *RelayDailyUsageSummaryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(relaydailyusagesummary.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.RelayKeyID(); exists {
			s.SetIgnore(relaydailyusagesummary.FieldRelayKeyID)
		}
		if _, exists := u.create.mutation.ProjectID(); exists {
			s.SetIgnore(relaydailyusagesummary.FieldProjectID)
		}
		if _, exists := u.create.mutation.StatDate(); exists {
			s.SetIgnore(relaydailyusagesummary.FieldStatDate)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelayDailyUsageSummary.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RelayDailyUsageSummaryUpsertOne) Ignore() *RelayDailyUsageSummaryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelayDailyUsageSummaryUpsertOne) DoNothing() *RelayDailyUsageSummaryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelayDailyUsageSummaryCreate.OnConflict
// documentation for more info.
func (u *RelayDailyUsageSummaryUpsertOne) Update(set func(*RelayDailyUsageSummaryUpsert)) *RelayDailyUsageSummaryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelayDailyUsageSummaryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelayDailyUsageSummaryUpsertOne) SetUpdatedAt(v time.Time) *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsertOne) UpdateUpdatedAt() *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRequestCount sets the "request_count" field.
func (u *RelayDailyUsageSummaryUpsertOne) SetRequestCount(v int64) *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.SetRequestCount(v)
	})
}

// AddRequestCount adds v to the "request_count" field.
func (u *RelayDailyUsageSummaryUpsertOne) AddRequestCount(v int64) *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.AddRequestCount(v)
	})
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsertOne) UpdateRequestCount() *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.UpdateRequestCount()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *RelayDailyUsageSummaryUpsertOne) SetTotalTokens(v int64) *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *RelayDailyUsageSummaryUpsertOne) AddTotalTokens(v int64) *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsertOne) UpdateTotalTokens() *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetTotalCharge sets the "total_charge" field.
func (u *RelayDailyUsageSummaryUpsertOne) SetTotalCharge(v string) *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.SetTotalCharge(v)
	})
}

// UpdateTotalCharge sets the "total_charge" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsertOne) UpdateTotalCharge() *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.UpdateTotalCharge()
	})
}

// SetTotalUpstreamCost sets the "total_upstream_cost" field.
func (u *RelayDailyUsageSummaryUpsertOne) SetTotalUpstreamCost(v string) *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.SetTotalUpstreamCost(v)
	})
}

// UpdateTotalUpstreamCost sets the "total_upstream_cost" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsertOne) UpdateTotalUpstreamCost() *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.UpdateTotalUpstreamCost()
	})
}

// SetLastRequestID sets the "last_request_id" field.
func (u *RelayDailyUsageSummaryUpsertOne) SetLastRequestID(v int) *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.SetLastRequestID(v)
	})
}

// AddLastRequestID adds v to the "last_request_id" field.
func (u *RelayDailyUsageSummaryUpsertOne) AddLastRequestID(v int) *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.AddLastRequestID(v)
	})
}

// UpdateLastRequestID sets the "last_request_id" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsertOne) UpdateLastRequestID() *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.UpdateLastRequestID()
	})
}

// ClearLastRequestID clears the value of the "last_request_id" field.
func (u *RelayDailyUsageSummaryUpsertOne) ClearLastRequestID() *RelayDailyUsageSummaryUpsertOne {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.ClearLastRequestID()
	})
}

// Exec executes the query.
func (u *RelayDailyUsageSummaryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelayDailyUsageSummaryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelayDailyUsageSummaryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RelayDailyUsageSummaryUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RelayDailyUsageSummaryUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RelayDailyUsageSummaryCreateBulk is the builder for creating many RelayDailyUsageSummary entities in bulk.
type RelayDailyUsageSummaryCreateBulk struct {
	config
	err      error
	builders []*RelayDailyUsageSummaryCreate
	conflict []sql.ConflictOption
}

// Save creates the RelayDailyUsageSummary entities in the database.
func (_c *RelayDailyUsageSummaryCreateBulk) Save(ctx context.Context) ([]*RelayDailyUsageSummary, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RelayDailyUsageSummary, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelayDailyUsageSummaryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RelayDailyUsageSummaryCreateBulk) SaveX(ctx context.Context) []*RelayDailyUsageSummary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelayDailyUsageSummaryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelayDailyUsageSummaryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelayDailyUsageSummary.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelayDailyUsageSummaryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RelayDailyUsageSummaryCreateBulk) OnConflict(opts ...sql.ConflictOption) *RelayDailyUsageSummaryUpsertBulk {
	_c.conflict = opts
	return &RelayDailyUsageSummaryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelayDailyUsageSummary.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelayDailyUsageSummaryCreateBulk) OnConflictColumns(columns ...string) *RelayDailyUsageSummaryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelayDailyUsageSummaryUpsertBulk{
		create: _c,
	}
}

// RelayDailyUsageSummaryUpsertBulk is the builder for "upsert"-ing
// a bulk of RelayDailyUsageSummary nodes.
type RelayDailyUsageSummaryUpsertBulk struct {
	create *RelayDailyUsageSummaryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RelayDailyUsageSummary.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelayDailyUsageSummaryUpsertBulk) UpdateNewValues() *RelayDailyUsageSummaryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(relaydailyusagesummary.FieldCreatedAt)
			}
			if _, exists := b.mutation.RelayKeyID(); exists {
				s.SetIgnore(relaydailyusagesummary.FieldRelayKeyID)
			}
			if _, exists := b.mutation.ProjectID(); exists {
				s.SetIgnore(relaydailyusagesummary.FieldProjectID)
			}
			if _, exists := b.mutation.StatDate(); exists {
				s.SetIgnore(relaydailyusagesummary.FieldStatDate)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelayDailyUsageSummary.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RelayDailyUsageSummaryUpsertBulk) Ignore() *RelayDailyUsageSummaryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelayDailyUsageSummaryUpsertBulk) DoNothing() *RelayDailyUsageSummaryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelayDailyUsageSummaryCreateBulk.OnConflict
// documentation for more info.
func (u *RelayDailyUsageSummaryUpsertBulk) Update(set func(*RelayDailyUsageSummaryUpsert)) *RelayDailyUsageSummaryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelayDailyUsageSummaryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelayDailyUsageSummaryUpsertBulk) SetUpdatedAt(v time.Time) *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsertBulk) UpdateUpdatedAt() *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRequestCount sets the "request_count" field.
func (u *RelayDailyUsageSummaryUpsertBulk) SetRequestCount(v int64) *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.SetRequestCount(v)
	})
}

// AddRequestCount adds v to the "request_count" field.
func (u *RelayDailyUsageSummaryUpsertBulk) AddRequestCount(v int64) *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.AddRequestCount(v)
	})
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsertBulk) UpdateRequestCount() *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.UpdateRequestCount()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *RelayDailyUsageSummaryUpsertBulk) SetTotalTokens(v int64) *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *RelayDailyUsageSummaryUpsertBulk) AddTotalTokens(v int64) *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsertBulk) UpdateTotalTokens() *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetTotalCharge sets the "total_charge" field.
func (u *RelayDailyUsageSummaryUpsertBulk) SetTotalCharge(v string) *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.SetTotalCharge(v)
	})
}

// UpdateTotalCharge sets the "total_charge" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsertBulk) UpdateTotalCharge() *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.UpdateTotalCharge()
	})
}

// SetTotalUpstreamCost sets the "total_upstream_cost" field.
func (u *RelayDailyUsageSummaryUpsertBulk) SetTotalUpstreamCost(v string) *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.SetTotalUpstreamCost(v)
	})
}

// UpdateTotalUpstreamCost sets the "total_upstream_cost" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsertBulk) UpdateTotalUpstreamCost() *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.UpdateTotalUpstreamCost()
	})
}

// SetLastRequestID sets the "last_request_id" field.
func (u *RelayDailyUsageSummaryUpsertBulk) SetLastRequestID(v int) *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.SetLastRequestID(v)
	})
}

// AddLastRequestID adds v to the "last_request_id" field.
func (u *RelayDailyUsageSummaryUpsertBulk) AddLastRequestID(v int) *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.AddLastRequestID(v)
	})
}

// UpdateLastRequestID sets the "last_request_id" field to the value that was provided on create.
func (u *RelayDailyUsageSummaryUpsertBulk) UpdateLastRequestID() *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.UpdateLastRequestID()
	})
}

// ClearLastRequestID clears the value of the "last_request_id" field.
func (u *RelayDailyUsageSummaryUpsertBulk) ClearLastRequestID() *RelayDailyUsageSummaryUpsertBulk {
	return u.Update(func(s *RelayDailyUsageSummaryUpsert) {
		s.ClearLastRequestID()
	})
}

// Exec executes the query.
func (u *RelayDailyUsageSummaryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RelayDailyUsageSummaryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelayDailyUsageSummaryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelayDailyUsageSummaryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
