// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/relayproductchannel"
)

// RelayProductChannelDelete is the builder for deleting a RelayProductChannel entity.
type RelayProductChannelDelete struct {
	config
	hooks    []Hook
	mutation *RelayProductChannelMutation
}

// Where appends a list predicates to the RelayProductChannelDelete builder.
func (_d *RelayProductChannelDelete) Where(ps ...predicate.RelayProductChannel) *RelayProductChannelDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RelayProductChannelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RelayProductChannelDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RelayProductChannelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(relayproductchannel.Table, sqlgraph.NewFieldSpec(relayproductchannel.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RelayProductChannelDeleteOne is the builder for deleting a single RelayProductChannel entity.
type RelayProductChannelDeleteOne struct {
	_d *RelayProductChannelDelete
}

// Where appends a list predicates to the RelayProductChannelDelete builder.
func (_d *RelayProductChannelDeleteOne) Where(ps ...predicate.RelayProductChannel) *RelayProductChannelDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RelayProductChannelDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{relayproductchannel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RelayProductChannelDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
