// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/relayproduct"
)

// RelayProduct is the model entity for the RelayProduct schema.
type RelayProduct struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Operator-facing unique relay product code
	Code string `json:"code,omitempty"`
	// Display name for the sellable shared-capacity product
	Name string `json:"name,omitempty"`
	// High-level provider family exposed by this product
	ProviderType relayproduct.ProviderType `json:"provider_type,omitempty"`
	// MVP keeps all relay products on shared upstream capacity
	AccessMode relayproduct.AccessMode `json:"access_mode,omitempty"`
	// Whether the product uses prepaid balance or quota-only access
	BillingMode relayproduct.BillingMode `json:"billing_mode,omitempty"`
	// Lifecycle status for operator product management
	Status relayproduct.Status `json:"status,omitempty"`
	// Settlement currency used by downstream billing presentation
	Currency string `json:"currency,omitempty"`
	// Opaque downstream pricing rules kept separate from upstream usage cost facts
	ListPriceConfig map[string]interface{} `json:"list_price_config,omitempty"`
	// Models exposed by this relay product at the catalog layer
	AllowedModels []string `json:"allowed_models,omitempty"`
	// Default request timeout applied to downstream calls for this product
	RequestTimeoutSeconds int `json:"request_timeout_seconds,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelayProductQuery when eager-loading is set.
	Edges        RelayProductEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelayProductEdges holds the relations/edges for other nodes in the graph.
type RelayProductEdges struct {
	// ChannelBindings holds the value of the channel_bindings edge.
	ChannelBindings []*RelayProductChannel `json:"channel_bindings,omitempty"`
	// RelayKeys holds the value of the relay_keys edge.
	RelayKeys []*RelayKey `json:"relay_keys,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedChannelBindings map[string][]*RelayProductChannel
	namedRelayKeys       map[string][]*RelayKey
}

// ChannelBindingsOrErr returns the ChannelBindings value or an error if the edge
// was not loaded in eager-loading.
func (e RelayProductEdges) ChannelBindingsOrErr() ([]*RelayProductChannel, error) {
	if e.loadedTypes[0] {
		return e.ChannelBindings, nil
	}
	return nil, &NotLoadedError{edge: "channel_bindings"}
}

// RelayKeysOrErr returns the RelayKeys value or an error if the edge
// was not loaded in eager-loading.
func (e RelayProductEdges) RelayKeysOrErr() ([]*RelayKey, error) {
	if e.loadedTypes[1] {
		return e.RelayKeys, nil
	}
	return nil, &NotLoadedError{edge: "relay_keys"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelayProduct) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relayproduct.FieldListPriceConfig, relayproduct.FieldAllowedModels:
			values[i] = new([]byte)
		case relayproduct.FieldID, relayproduct.FieldDeletedAt, relayproduct.FieldRequestTimeoutSeconds:
			values[i] = new(sql.NullInt64)
		case relayproduct.FieldCode, relayproduct.FieldName, relayproduct.FieldProviderType, relayproduct.FieldAccessMode, relayproduct.FieldBillingMode, relayproduct.FieldStatus, relayproduct.FieldCurrency:
			values[i] = new(sql.NullString)
		case relayproduct.FieldCreatedAt, relayproduct.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelayProduct fields.
func (_m *RelayProduct) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relayproduct.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case relayproduct.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case relayproduct.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case relayproduct.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case relayproduct.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case relayproduct.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case relayproduct.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				_m.ProviderType = relayproduct.ProviderType(value.String)
			}
		case relayproduct.FieldAccessMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_mode", values[i])
			} else if value.Valid {
				_m.AccessMode = relayproduct.AccessMode(value.String)
			}
		case relayproduct.FieldBillingMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_mode", values[i])
			} else if value.Valid {
				_m.BillingMode = relayproduct.BillingMode(value.String)
			}
		case relayproduct.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = relayproduct.Status(value.String)
			}
		case relayproduct.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case relayproduct.FieldListPriceConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field list_price_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ListPriceConfig); err != nil {
					return fmt.Errorf("unmarshal field list_price_config: %w", err)
				}
			}
		case relayproduct.FieldAllowedModels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_models", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedModels); err != nil {
					return fmt.Errorf("unmarshal field allowed_models: %w", err)
				}
			}
		case relayproduct.FieldRequestTimeoutSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_timeout_seconds", values[i])
			} else if value.Valid {
				_m.RequestTimeoutSeconds = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelayProduct.
// This includes values selected through modifiers, order, etc.
func (_m *RelayProduct) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannelBindings queries the "channel_bindings" edge of the RelayProduct entity.
func (_m *RelayProduct) QueryChannelBindings() *RelayProductChannelQuery {
	return NewRelayProductClient(_m.config).QueryChannelBindings(_m)
}

// QueryRelayKeys queries the "relay_keys" edge of the RelayProduct entity.
func (_m *RelayProduct) QueryRelayKeys() *RelayKeyQuery {
	return NewRelayProductClient(_m.config).QueryRelayKeys(_m)
}

// Update returns a builder for updating this RelayProduct.
// Note that you need to call RelayProduct.Unwrap() before calling this method if this RelayProduct
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelayProduct) Update() *RelayProductUpdateOne {
	return NewRelayProductClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelayProduct entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelayProduct) Unwrap() *RelayProduct {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelayProduct is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelayProduct) String() string {
	var builder strings.Builder
	builder.WriteString("RelayProduct(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderType))
	builder.WriteString(", ")
	builder.WriteString("access_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccessMode))
	builder.WriteString(", ")
	builder.WriteString("billing_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillingMode))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("list_price_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.ListPriceConfig))
	builder.WriteString(", ")
	builder.WriteString("allowed_models=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedModels))
	builder.WriteString(", ")
	builder.WriteString("request_timeout_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestTimeoutSeconds))
	builder.WriteByte(')')
	return builder.String()
}

// NamedChannelBindings returns the ChannelBindings named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *RelayProduct) NamedChannelBindings(name string) ([]*RelayProductChannel, error) {
	if _m.Edges.namedChannelBindings == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedChannelBindings[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *RelayProduct) appendNamedChannelBindings(name string, edges ...*RelayProductChannel) {
	if _m.Edges.namedChannelBindings == nil {
		_m.Edges.namedChannelBindings = make(map[string][]*RelayProductChannel)
	}
	if len(edges) == 0 {
		_m.Edges.namedChannelBindings[name] = []*RelayProductChannel{}
	} else {
		_m.Edges.namedChannelBindings[name] = append(_m.Edges.namedChannelBindings[name], edges...)
	}
}

// NamedRelayKeys returns the RelayKeys named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *RelayProduct) NamedRelayKeys(name string) ([]*RelayKey, error) {
	if _m.Edges.namedRelayKeys == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedRelayKeys[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *RelayProduct) appendNamedRelayKeys(name string, edges ...*RelayKey) {
	if _m.Edges.namedRelayKeys == nil {
		_m.Edges.namedRelayKeys = make(map[string][]*RelayKey)
	}
	if len(edges) == 0 {
		_m.Edges.namedRelayKeys[name] = []*RelayKey{}
	} else {
		_m.Edges.namedRelayKeys[name] = append(_m.Edges.namedRelayKeys[name], edges...)
	}
}

// RelayProducts is a parsable slice of RelayProduct.
type RelayProducts []*RelayProduct
