// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/relayproduct"
	"github.com/looplj/axonhub/internal/ent/relayproductchannel"
)

// RelayProductChannel is the model entity for the RelayProductChannel schema.
type RelayProductChannel struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Owning relay product id
	ProductID int `json:"product_id,omitempty"`
	// Bound upstream channel id
	ChannelID int `json:"channel_id,omitempty"`
	// Lower values are selected first during pool candidate ordering
	Priority int `json:"priority,omitempty"`
	// Relative weight when multiple bindings share the same priority
	Weight int `json:"weight,omitempty"`
	// Binding-level availability inside the product pool
	Status relayproductchannel.Status `json:"status,omitempty"`
	// Whether routing may continue to lower-priority bindings when this binding is unsuitable
	AllowFallback bool `json:"allow_fallback,omitempty"`
	// Opaque per-binding model filter rules for future router matching
	ModelFilter any `json:"model_filter,omitempty"`
	// Optional per-binding inflight cap before routing falls back to another candidate
	MaxInflight *int `json:"max_inflight,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelayProductChannelQuery when eager-loading is set.
	Edges        RelayProductChannelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelayProductChannelEdges holds the relations/edges for other nodes in the graph.
type RelayProductChannelEdges struct {
	// Product holds the value of the product edge.
	Product *RelayProduct `json:"product,omitempty"`
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelayProductChannelEdges) ProductOrErr() (*RelayProduct, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: relayproduct.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelayProductChannelEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelayProductChannel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relayproductchannel.FieldModelFilter:
			values[i] = new([]byte)
		case relayproductchannel.FieldAllowFallback:
			values[i] = new(sql.NullBool)
		case relayproductchannel.FieldID, relayproductchannel.FieldProductID, relayproductchannel.FieldChannelID, relayproductchannel.FieldPriority, relayproductchannel.FieldWeight, relayproductchannel.FieldMaxInflight:
			values[i] = new(sql.NullInt64)
		case relayproductchannel.FieldStatus:
			values[i] = new(sql.NullString)
		case relayproductchannel.FieldCreatedAt, relayproductchannel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelayProductChannel fields.
func (_m *RelayProductChannel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relayproductchannel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case relayproductchannel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case relayproductchannel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case relayproductchannel.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = int(value.Int64)
			}
		case relayproductchannel.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case relayproductchannel.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case relayproductchannel.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case relayproductchannel.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = relayproductchannel.Status(value.String)
			}
		case relayproductchannel.FieldAllowFallback:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_fallback", values[i])
			} else if value.Valid {
				_m.AllowFallback = value.Bool
			}
		case relayproductchannel.FieldModelFilter:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field model_filter", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ModelFilter); err != nil {
					return fmt.Errorf("unmarshal field model_filter: %w", err)
				}
			}
		case relayproductchannel.FieldMaxInflight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_inflight", values[i])
			} else if value.Valid {
				_m.MaxInflight = new(int)
				*_m.MaxInflight = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelayProductChannel.
// This includes values selected through modifiers, order, etc.
func (_m *RelayProductChannel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProduct queries the "product" edge of the RelayProductChannel entity.
func (_m *RelayProductChannel) QueryProduct() *RelayProductQuery {
	return NewRelayProductChannelClient(_m.config).QueryProduct(_m)
}

// QueryChannel queries the "channel" edge of the RelayProductChannel entity.
func (_m *RelayProductChannel) QueryChannel() *ChannelQuery {
	return NewRelayProductChannelClient(_m.config).QueryChannel(_m)
}

// Update returns a builder for updating this RelayProductChannel.
// Note that you need to call RelayProductChannel.Unwrap() before calling this method if this RelayProductChannel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelayProductChannel) Update() *RelayProductChannelUpdateOne {
	return NewRelayProductChannelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelayProductChannel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelayProductChannel) Unwrap() *RelayProductChannel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelayProductChannel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelayProductChannel) String() string {
	var builder strings.Builder
	builder.WriteString("RelayProductChannel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductID))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("allow_fallback=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowFallback))
	builder.WriteString(", ")
	builder.WriteString("model_filter=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelFilter))
	builder.WriteString(", ")
	if v := _m.MaxInflight; v != nil {
		builder.WriteString("max_inflight=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// RelayProductChannels is a parsable slice of RelayProductChannel.
type RelayProductChannels []*RelayProductChannel
