// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/relaywalletledgerentry"
)

// RelayWalletLedgerEntryUpdate is the builder for updating RelayWalletLedgerEntry entities.
type RelayWalletLedgerEntryUpdate struct {
	config
	hooks     []Hook
	mutation  *RelayWalletLedgerEntryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RelayWalletLedgerEntryUpdate builder.
func (_u *RelayWalletLedgerEntryUpdate) Where(ps ...predicate.RelayWalletLedgerEntry) *RelayWalletLedgerEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelayWalletLedgerEntryUpdate) SetUpdatedAt(v time.Time) *RelayWalletLedgerEntryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RelayWalletLedgerEntryMutation object of the builder.
func (_u *RelayWalletLedgerEntryUpdate) Mutation() *RelayWalletLedgerEntryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelayWalletLedgerEntryUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayWalletLedgerEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelayWalletLedgerEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayWalletLedgerEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelayWalletLedgerEntryUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if relaywalletledgerentry.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaywalletledgerentry.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := relaywalletledgerentry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayWalletLedgerEntryUpdate) check() error {
	if _u.mutation.RelayKeyCleared() && len(_u.mutation.RelayKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelayWalletLedgerEntry.relay_key"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RelayWalletLedgerEntryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RelayWalletLedgerEntryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RelayWalletLedgerEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaywalletledgerentry.Table, relaywalletledgerentry.Columns, sqlgraph.NewFieldSpec(relaywalletledgerentry.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaywalletledgerentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(relaywalletledgerentry.FieldRequestID, field.TypeInt)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(relaywalletledgerentry.FieldUsageLogID, field.TypeInt)
	}
	if _u.mutation.UpstreamCostCleared() {
		_spec.ClearField(relaywalletledgerentry.FieldUpstreamCost, field.TypeString)
	}
	if _u.mutation.PriceSnapshotCleared() {
		_spec.ClearField(relaywalletledgerentry.FieldPriceSnapshot, field.TypeJSON)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(relaywalletledgerentry.FieldOperatorUserID, field.TypeInt)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(relaywalletledgerentry.FieldRemark, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaywalletledgerentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelayWalletLedgerEntryUpdateOne is the builder for updating a single RelayWalletLedgerEntry entity.
type RelayWalletLedgerEntryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RelayWalletLedgerEntryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelayWalletLedgerEntryUpdateOne) SetUpdatedAt(v time.Time) *RelayWalletLedgerEntryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RelayWalletLedgerEntryMutation object of the builder.
func (_u *RelayWalletLedgerEntryUpdateOne) Mutation() *RelayWalletLedgerEntryMutation {
	return _u.mutation
}

// Where appends a list predicates to the RelayWalletLedgerEntryUpdate builder.
func (_u *RelayWalletLedgerEntryUpdateOne) Where(ps ...predicate.RelayWalletLedgerEntry) *RelayWalletLedgerEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelayWalletLedgerEntryUpdateOne) Select(field string, fields ...string) *RelayWalletLedgerEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RelayWalletLedgerEntry entity.
func (_u *RelayWalletLedgerEntryUpdateOne) Save(ctx context.Context) (*RelayWalletLedgerEntry, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayWalletLedgerEntryUpdateOne) SaveX(ctx context.Context) *RelayWalletLedgerEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelayWalletLedgerEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayWalletLedgerEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelayWalletLedgerEntryUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if relaywalletledgerentry.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaywalletledgerentry.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := relaywalletledgerentry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayWalletLedgerEntryUpdateOne) check() error {
	if _u.mutation.RelayKeyCleared() && len(_u.mutation.RelayKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelayWalletLedgerEntry.relay_key"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RelayWalletLedgerEntryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RelayWalletLedgerEntryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RelayWalletLedgerEntryUpdateOne) sqlSave(ctx context.Context) (_node *RelayWalletLedgerEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaywalletledgerentry.Table, relaywalletledgerentry.Columns, sqlgraph.NewFieldSpec(relaywalletledgerentry.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RelayWalletLedgerEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relaywalletledgerentry.FieldID)
		for _, f := range fields {
			if !relaywalletledgerentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relaywalletledgerentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaywalletledgerentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(relaywalletledgerentry.FieldRequestID, field.TypeInt)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(relaywalletledgerentry.FieldUsageLogID, field.TypeInt)
	}
	if _u.mutation.UpstreamCostCleared() {
		_spec.ClearField(relaywalletledgerentry.FieldUpstreamCost, field.TypeString)
	}
	if _u.mutation.PriceSnapshotCleared() {
		_spec.ClearField(relaywalletledgerentry.FieldPriceSnapshot, field.TypeJSON)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(relaywalletledgerentry.FieldOperatorUserID, field.TypeInt)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(relaywalletledgerentry.FieldRemark, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RelayWalletLedgerEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaywalletledgerentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
