// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/relaydailyusagesummary"
)

// RelayDailyUsageSummaryUpdate is the builder for updating RelayDailyUsageSummary entities.
type RelayDailyUsageSummaryUpdate struct {
	config
	hooks     []Hook
	mutation  *RelayDailyUsageSummaryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RelayDailyUsageSummaryUpdate builder.
func (_u *RelayDailyUsageSummaryUpdate) Where(ps ...predicate.RelayDailyUsageSummary) *RelayDailyUsageSummaryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelayDailyUsageSummaryUpdate) SetUpdatedAt(v time.Time) *RelayDailyUsageSummaryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *RelayDailyUsageSummaryUpdate) SetRequestCount(v int64) *RelayDailyUsageSummaryUpdate {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *RelayDailyUsageSummaryUpdate) SetNillableRequestCount(v *int64) *RelayDailyUsageSummaryUpdate {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *RelayDailyUsageSummaryUpdate) AddRequestCount(v int64) *RelayDailyUsageSummaryUpdate {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *RelayDailyUsageSummaryUpdate) SetTotalTokens(v int64) *RelayDailyUsageSummaryUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *RelayDailyUsageSummaryUpdate) SetNillableTotalTokens(v *int64) *RelayDailyUsageSummaryUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *RelayDailyUsageSummaryUpdate) AddTotalTokens(v int64) *RelayDailyUsageSummaryUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetTotalCharge sets the "total_charge" field.
func (_u *RelayDailyUsageSummaryUpdate) SetTotalCharge(v string) *RelayDailyUsageSummaryUpdate {
	_u.mutation.SetTotalCharge(v)
	return _u
}

// SetNillableTotalCharge sets the "total_charge" field if the given value is not nil.
func (_u *RelayDailyUsageSummaryUpdate) SetNillableTotalCharge(v *string) *RelayDailyUsageSummaryUpdate {
	if v != nil {
		_u.SetTotalCharge(*v)
	}
	return _u
}

// SetTotalUpstreamCost sets the "total_upstream_cost" field.
func (_u *RelayDailyUsageSummaryUpdate) SetTotalUpstreamCost(v string) *RelayDailyUsageSummaryUpdate {
	_u.mutation.SetTotalUpstreamCost(v)
	return _u
}

// SetNillableTotalUpstreamCost sets the "total_upstream_cost" field if the given value is not nil.
func (_u *RelayDailyUsageSummaryUpdate) SetNillableTotalUpstreamCost(v *string) *RelayDailyUsageSummaryUpdate {
	if v != nil {
		_u.SetTotalUpstreamCost(*v)
	}
	return _u
}

// SetLastRequestID sets the "last_request_id" field.
func (_u *RelayDailyUsageSummaryUpdate) SetLastRequestID(v int) *RelayDailyUsageSummaryUpdate {
	_u.mutation.ResetLastRequestID()
	_u.mutation.SetLastRequestID(v)
	return _u
}

// SetNillableLastRequestID sets the "last_request_id" field if the given value is not nil.
func (_u *RelayDailyUsageSummaryUpdate) SetNillableLastRequestID(v *int) *RelayDailyUsageSummaryUpdate {
	if v != nil {
		_u.SetLastRequestID(*v)
	}
	return _u
}

// AddLastRequestID adds value to the "last_request_id" field.
func (_u *RelayDailyUsageSummaryUpdate) AddLastRequestID(v int) *RelayDailyUsageSummaryUpdate {
	_u.mutation.AddLastRequestID(v)
	return _u
}

// ClearLastRequestID clears the value of the "last_request_id" field.
func (_u *RelayDailyUsageSummaryUpdate) ClearLastRequestID() *RelayDailyUsageSummaryUpdate {
	_u.mutation.ClearLastRequestID()
	return _u
}

// Mutation returns the RelayDailyUsageSummaryMutation object of the builder.
func (_u *RelayDailyUsageSummaryUpdate) Mutation() *RelayDailyUsageSummaryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelayDailyUsageSummaryUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayDailyUsageSummaryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelayDailyUsageSummaryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayDailyUsageSummaryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelayDailyUsageSummaryUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if relaydailyusagesummary.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaydailyusagesummary.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := relaydailyusagesummary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayDailyUsageSummaryUpdate) check() error {
	if _u.mutation.RelayKeyCleared() && len(_u.mutation.RelayKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelayDailyUsageSummary.relay_key"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RelayDailyUsageSummaryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RelayDailyUsageSummaryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RelayDailyUsageSummaryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaydailyusagesummary.Table, relaydailyusagesummary.Columns, sqlgraph.NewFieldSpec(relaydailyusagesummary.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaydailyusagesummary.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(relaydailyusagesummary.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(relaydailyusagesummary.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(relaydailyusagesummary.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(relaydailyusagesummary.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalCharge(); ok {
		_spec.SetField(relaydailyusagesummary.FieldTotalCharge, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalUpstreamCost(); ok {
		_spec.SetField(relaydailyusagesummary.FieldTotalUpstreamCost, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastRequestID(); ok {
		_spec.SetField(relaydailyusagesummary.FieldLastRequestID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastRequestID(); ok {
		_spec.AddField(relaydailyusagesummary.FieldLastRequestID, field.TypeInt, value)
	}
	if _u.mutation.LastRequestIDCleared() {
		_spec.ClearField(relaydailyusagesummary.FieldLastRequestID, field.TypeInt)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaydailyusagesummary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelayDailyUsageSummaryUpdateOne is the builder for updating a single RelayDailyUsageSummary entity.
type RelayDailyUsageSummaryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RelayDailyUsageSummaryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelayDailyUsageSummaryUpdateOne) SetUpdatedAt(v time.Time) *RelayDailyUsageSummaryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *RelayDailyUsageSummaryUpdateOne) SetRequestCount(v int64) *RelayDailyUsageSummaryUpdateOne {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *RelayDailyUsageSummaryUpdateOne) SetNillableRequestCount(v *int64) *RelayDailyUsageSummaryUpdateOne {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *RelayDailyUsageSummaryUpdateOne) AddRequestCount(v int64) *RelayDailyUsageSummaryUpdateOne {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *RelayDailyUsageSummaryUpdateOne) SetTotalTokens(v int64) *RelayDailyUsageSummaryUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *RelayDailyUsageSummaryUpdateOne) SetNillableTotalTokens(v *int64) *RelayDailyUsageSummaryUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *RelayDailyUsageSummaryUpdateOne) AddTotalTokens(v int64) *RelayDailyUsageSummaryUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetTotalCharge sets the "total_charge" field.
func (_u *RelayDailyUsageSummaryUpdateOne) SetTotalCharge(v string) *RelayDailyUsageSummaryUpdateOne {
	_u.mutation.SetTotalCharge(v)
	return _u
}

// SetNillableTotalCharge sets the "total_charge" field if the given value is not nil.
func (_u *RelayDailyUsageSummaryUpdateOne) SetNillableTotalCharge(v *string) *RelayDailyUsageSummaryUpdateOne {
	if v != nil {
		_u.SetTotalCharge(*v)
	}
	return _u
}

// SetTotalUpstreamCost sets the "total_upstream_cost" field.
func (_u *RelayDailyUsageSummaryUpdateOne) SetTotalUpstreamCost(v string) *RelayDailyUsageSummaryUpdateOne {
	_u.mutation.SetTotalUpstreamCost(v)
	return _u
}

// SetNillableTotalUpstreamCost sets the "total_upstream_cost" field if the given value is not nil.
func (_u *RelayDailyUsageSummaryUpdateOne) SetNillableTotalUpstreamCost(v *string) *RelayDailyUsageSummaryUpdateOne {
	if v != nil {
		_u.SetTotalUpstreamCost(*v)
	}
	return _u
}

// SetLastRequestID sets the "last_request_id" field.
func (_u *RelayDailyUsageSummaryUpdateOne) SetLastRequestID(v int) *RelayDailyUsageSummaryUpdateOne {
	_u.mutation.ResetLastRequestID()
	_u.mutation.SetLastRequestID(v)
	return _u
}

// SetNillableLastRequestID sets the "last_request_id" field if the given value is not nil.
func (_u *RelayDailyUsageSummaryUpdateOne) SetNillableLastRequestID(v *int) *RelayDailyUsageSummaryUpdateOne {
	if v != nil {
		_u.SetLastRequestID(*v)
	}
	return _u
}

// AddLastRequestID adds value to the "last_request_id" field.
func (_u *RelayDailyUsageSummaryUpdateOne) AddLastRequestID(v int) *RelayDailyUsageSummaryUpdateOne {
	_u.mutation.AddLastRequestID(v)
	return _u
}

// ClearLastRequestID clears the value of the "last_request_id" field.
func (_u *RelayDailyUsageSummaryUpdateOne) ClearLastRequestID() *RelayDailyUsageSummaryUpdateOne {
	_u.mutation.ClearLastRequestID()
	return _u
}

// Mutation returns the RelayDailyUsageSummaryMutation object of the builder.
func (_u *RelayDailyUsageSummaryUpdateOne) Mutation() *RelayDailyUsageSummaryMutation {
	return _u.mutation
}

// Where appends a list predicates to the RelayDailyUsageSummaryUpdate builder.
func (_u *RelayDailyUsageSummaryUpdateOne) Where(ps ...predicate.RelayDailyUsageSummary) *RelayDailyUsageSummaryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelayDailyUsageSummaryUpdateOne) Select(field string, fields ...string) *RelayDailyUsageSummaryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RelayDailyUsageSummary entity.
func (_u *RelayDailyUsageSummaryUpdateOne) Save(ctx context.Context) (*RelayDailyUsageSummary, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayDailyUsageSummaryUpdateOne) SaveX(ctx context.Context) *RelayDailyUsageSummary {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelayDailyUsageSummaryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayDailyUsageSummaryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelayDailyUsageSummaryUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if relaydailyusagesummary.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized relaydailyusagesummary.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := relaydailyusagesummary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayDailyUsageSummaryUpdateOne) check() error {
	if _u.mutation.RelayKeyCleared() && len(_u.mutation.RelayKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelayDailyUsageSummary.relay_key"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RelayDailyUsageSummaryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RelayDailyUsageSummaryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RelayDailyUsageSummaryUpdateOne) sqlSave(ctx context.Context) (_node *RelayDailyUsageSummary, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaydailyusagesummary.Table, relaydailyusagesummary.Columns, sqlgraph.NewFieldSpec(relaydailyusagesummary.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RelayDailyUsageSummary.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relaydailyusagesummary.FieldID)
		for _, f := range fields {
			if !relaydailyusagesummary.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relaydailyusagesummary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaydailyusagesummary.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(relaydailyusagesummary.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(relaydailyusagesummary.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(relaydailyusagesummary.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(relaydailyusagesummary.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalCharge(); ok {
		_spec.SetField(relaydailyusagesummary.FieldTotalCharge, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalUpstreamCost(); ok {
		_spec.SetField(relaydailyusagesummary.FieldTotalUpstreamCost, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastRequestID(); ok {
		_spec.SetField(relaydailyusagesummary.FieldLastRequestID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastRequestID(); ok {
		_spec.AddField(relaydailyusagesummary.FieldLastRequestID, field.TypeInt, value)
	}
	if _u.mutation.LastRequestIDCleared() {
		_spec.ClearField(relaydailyusagesummary.FieldLastRequestID, field.TypeInt)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RelayDailyUsageSummary{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaydailyusagesummary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
