// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/relaykey"
	"github.com/looplj/axonhub/internal/ent/relayproduct"
	"github.com/looplj/axonhub/internal/ent/relaywallet"
	"github.com/looplj/axonhub/internal/ent/user"
)

// RelayKey is the model entity for the RelayKey schema.
type RelayKey struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Existing API key that authenticates this downstream Relay Sub-Key
	APIKeyID int `json:"api_key_id,omitempty"`
	// Project scope for buyer isolation
	ProjectID int `json:"project_id,omitempty"`
	// Relay product sold to this Sub-Key
	ProductID int `json:"product_id,omitempty"`
	// Optional project user that owns or operates this Sub-Key
	OwnerUserID *int `json:"owner_user_id,omitempty"`
	// Operator/project facing display name
	DisplayName string `json:"display_name,omitempty"`
	// Persistent Relay key lifecycle state
	Status relaykey.Status `json:"status,omitempty"`
	// Whether access requires wallet balance or only hard quotas
	BalanceMode relaykey.BalanceMode `json:"balance_mode,omitempty"`
	// Optional per-day request hard limit
	DailyRequestLimit *int64 `json:"daily_request_limit,omitempty"`
	// Optional per-day token hard limit
	DailyTokenLimit *int64 `json:"daily_token_limit,omitempty"`
	// Optional monthly charge limit stored as a decimal string
	MonthlyCostLimit *string `json:"monthly_cost_limit,omitempty"`
	// Optional concurrent request limit
	ConcurrencyLimit *int64 `json:"concurrency_limit,omitempty"`
	// Optional expiration time after which access is denied
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Last successful runtime access timestamp
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelayKeyQuery when eager-loading is set.
	Edges        RelayKeyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelayKeyEdges holds the relations/edges for other nodes in the graph.
type RelayKeyEdges struct {
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Product holds the value of the product edge.
	Product *RelayProduct `json:"product,omitempty"`
	// OwnerUser holds the value of the owner_user edge.
	OwnerUser *User `json:"owner_user,omitempty"`
	// Wallet holds the value of the wallet edge.
	Wallet *RelayWallet `json:"wallet,omitempty"`
	// LedgerEntries holds the value of the ledger_entries edge.
	LedgerEntries []*RelayWalletLedgerEntry `json:"ledger_entries,omitempty"`
	// DailyUsageSummaries holds the value of the daily_usage_summaries edge.
	DailyUsageSummaries []*RelayDailyUsageSummary `json:"daily_usage_summaries,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
	// totalCount holds the count of the edges above.
	totalCount [7]map[string]int

	namedLedgerEntries       map[string][]*RelayWalletLedgerEntry
	namedDailyUsageSummaries map[string][]*RelayDailyUsageSummary
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelayKeyEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelayKeyEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelayKeyEdges) ProductOrErr() (*RelayProduct, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: relayproduct.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// OwnerUserOrErr returns the OwnerUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelayKeyEdges) OwnerUserOrErr() (*User, error) {
	if e.OwnerUser != nil {
		return e.OwnerUser, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner_user"}
}

// WalletOrErr returns the Wallet value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelayKeyEdges) WalletOrErr() (*RelayWallet, error) {
	if e.Wallet != nil {
		return e.Wallet, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: relaywallet.Label}
	}
	return nil, &NotLoadedError{edge: "wallet"}
}

// LedgerEntriesOrErr returns the LedgerEntries value or an error if the edge
// was not loaded in eager-loading.
func (e RelayKeyEdges) LedgerEntriesOrErr() ([]*RelayWalletLedgerEntry, error) {
	if e.loadedTypes[5] {
		return e.LedgerEntries, nil
	}
	return nil, &NotLoadedError{edge: "ledger_entries"}
}

// DailyUsageSummariesOrErr returns the DailyUsageSummaries value or an error if the edge
// was not loaded in eager-loading.
func (e RelayKeyEdges) DailyUsageSummariesOrErr() ([]*RelayDailyUsageSummary, error) {
	if e.loadedTypes[6] {
		return e.DailyUsageSummaries, nil
	}
	return nil, &NotLoadedError{edge: "daily_usage_summaries"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelayKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relaykey.FieldID, relaykey.FieldDeletedAt, relaykey.FieldAPIKeyID, relaykey.FieldProjectID, relaykey.FieldProductID, relaykey.FieldOwnerUserID, relaykey.FieldDailyRequestLimit, relaykey.FieldDailyTokenLimit, relaykey.FieldConcurrencyLimit:
			values[i] = new(sql.NullInt64)
		case relaykey.FieldDisplayName, relaykey.FieldStatus, relaykey.FieldBalanceMode, relaykey.FieldMonthlyCostLimit:
			values[i] = new(sql.NullString)
		case relaykey.FieldCreatedAt, relaykey.FieldUpdatedAt, relaykey.FieldExpiresAt, relaykey.FieldLastUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelayKey fields.
func (_m *RelayKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relaykey.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case relaykey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case relaykey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case relaykey.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case relaykey.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = int(value.Int64)
			}
		case relaykey.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case relaykey.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = int(value.Int64)
			}
		case relaykey.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = new(int)
				*_m.OwnerUserID = int(value.Int64)
			}
		case relaykey.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case relaykey.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = relaykey.Status(value.String)
			}
		case relaykey.FieldBalanceMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field balance_mode", values[i])
			} else if value.Valid {
				_m.BalanceMode = relaykey.BalanceMode(value.String)
			}
		case relaykey.FieldDailyRequestLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_request_limit", values[i])
			} else if value.Valid {
				_m.DailyRequestLimit = new(int64)
				*_m.DailyRequestLimit = value.Int64
			}
		case relaykey.FieldDailyTokenLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_token_limit", values[i])
			} else if value.Valid {
				_m.DailyTokenLimit = new(int64)
				*_m.DailyTokenLimit = value.Int64
			}
		case relaykey.FieldMonthlyCostLimit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_cost_limit", values[i])
			} else if value.Valid {
				_m.MonthlyCostLimit = new(string)
				*_m.MonthlyCostLimit = value.String
			}
		case relaykey.FieldConcurrencyLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency_limit", values[i])
			} else if value.Valid {
				_m.ConcurrencyLimit = new(int64)
				*_m.ConcurrencyLimit = value.Int64
			}
		case relaykey.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case relaykey.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelayKey.
// This includes values selected through modifiers, order, etc.
func (_m *RelayKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPIKey queries the "api_key" edge of the RelayKey entity.
func (_m *RelayKey) QueryAPIKey() *APIKeyQuery {
	return NewRelayKeyClient(_m.config).QueryAPIKey(_m)
}

// QueryProject queries the "project" edge of the RelayKey entity.
func (_m *RelayKey) QueryProject() *ProjectQuery {
	return NewRelayKeyClient(_m.config).QueryProject(_m)
}

// QueryProduct queries the "product" edge of the RelayKey entity.
func (_m *RelayKey) QueryProduct() *RelayProductQuery {
	return NewRelayKeyClient(_m.config).QueryProduct(_m)
}

// QueryOwnerUser queries the "owner_user" edge of the RelayKey entity.
func (_m *RelayKey) QueryOwnerUser() *UserQuery {
	return NewRelayKeyClient(_m.config).QueryOwnerUser(_m)
}

// QueryWallet queries the "wallet" edge of the RelayKey entity.
func (_m *RelayKey) QueryWallet() *RelayWalletQuery {
	return NewRelayKeyClient(_m.config).QueryWallet(_m)
}

// QueryLedgerEntries queries the "ledger_entries" edge of the RelayKey entity.
func (_m *RelayKey) QueryLedgerEntries() *RelayWalletLedgerEntryQuery {
	return NewRelayKeyClient(_m.config).QueryLedgerEntries(_m)
}

// QueryDailyUsageSummaries queries the "daily_usage_summaries" edge of the RelayKey entity.
func (_m *RelayKey) QueryDailyUsageSummaries() *RelayDailyUsageSummaryQuery {
	return NewRelayKeyClient(_m.config).QueryDailyUsageSummaries(_m)
}

// Update returns a builder for updating this RelayKey.
// Note that you need to call RelayKey.Unwrap() before calling this method if this RelayKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelayKey) Update() *RelayKeyUpdateOne {
	return NewRelayKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelayKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelayKey) Unwrap() *RelayKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelayKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelayKey) String() string {
	var builder strings.Builder
	builder.WriteString("RelayKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductID))
	builder.WriteString(", ")
	if v := _m.OwnerUserID; v != nil {
		builder.WriteString("owner_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("balance_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceMode))
	builder.WriteString(", ")
	if v := _m.DailyRequestLimit; v != nil {
		builder.WriteString("daily_request_limit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DailyTokenLimit; v != nil {
		builder.WriteString("daily_token_limit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MonthlyCostLimit; v != nil {
		builder.WriteString("monthly_cost_limit=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ConcurrencyLimit; v != nil {
		builder.WriteString("concurrency_limit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// NamedLedgerEntries returns the LedgerEntries named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *RelayKey) NamedLedgerEntries(name string) ([]*RelayWalletLedgerEntry, error) {
	if _m.Edges.namedLedgerEntries == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedLedgerEntries[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *RelayKey) appendNamedLedgerEntries(name string, edges ...*RelayWalletLedgerEntry) {
	if _m.Edges.namedLedgerEntries == nil {
		_m.Edges.namedLedgerEntries = make(map[string][]*RelayWalletLedgerEntry)
	}
	if len(edges) == 0 {
		_m.Edges.namedLedgerEntries[name] = []*RelayWalletLedgerEntry{}
	} else {
		_m.Edges.namedLedgerEntries[name] = append(_m.Edges.namedLedgerEntries[name], edges...)
	}
}

// NamedDailyUsageSummaries returns the DailyUsageSummaries named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *RelayKey) NamedDailyUsageSummaries(name string) ([]*RelayDailyUsageSummary, error) {
	if _m.Edges.namedDailyUsageSummaries == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedDailyUsageSummaries[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *RelayKey) appendNamedDailyUsageSummaries(name string, edges ...*RelayDailyUsageSummary) {
	if _m.Edges.namedDailyUsageSummaries == nil {
		_m.Edges.namedDailyUsageSummaries = make(map[string][]*RelayDailyUsageSummary)
	}
	if len(edges) == 0 {
		_m.Edges.namedDailyUsageSummaries[name] = []*RelayDailyUsageSummary{}
	} else {
		_m.Edges.namedDailyUsageSummaries[name] = append(_m.Edges.namedDailyUsageSummaries[name], edges...)
	}
}

// RelayKeys is a parsable slice of RelayKey.
type RelayKeys []*RelayKey
