// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/relaykey"
	"github.com/looplj/axonhub/internal/ent/relaywallet"
)

// RelayWallet is the model entity for the RelayWallet schema.
type RelayWallet struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Relay key that owns this balance snapshot
	RelayKeyID int `json:"relay_key_id,omitempty"`
	// Project scope copied from the owning Relay key for privacy filters
	ProjectID int `json:"project_id,omitempty"`
	// Wallet currency
	Currency string `json:"currency,omitempty"`
	// Spendable balance stored as a decimal string
	AvailableAmount string `json:"available_amount,omitempty"`
	// Frozen balance stored as a decimal string
	FrozenAmount string `json:"frozen_amount,omitempty"`
	// Allowed overdraft stored as a decimal string
	OverdraftLimit string `json:"overdraft_limit,omitempty"`
	// Optimistic-lock version for wallet snapshot updates
	Version int64 `json:"version,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelayWalletQuery when eager-loading is set.
	Edges        RelayWalletEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelayWalletEdges holds the relations/edges for other nodes in the graph.
type RelayWalletEdges struct {
	// RelayKey holds the value of the relay_key edge.
	RelayKey *RelayKey `json:"relay_key,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// RelayKeyOrErr returns the RelayKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelayWalletEdges) RelayKeyOrErr() (*RelayKey, error) {
	if e.RelayKey != nil {
		return e.RelayKey, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: relaykey.Label}
	}
	return nil, &NotLoadedError{edge: "relay_key"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelayWallet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relaywallet.FieldID, relaywallet.FieldRelayKeyID, relaywallet.FieldProjectID, relaywallet.FieldVersion:
			values[i] = new(sql.NullInt64)
		case relaywallet.FieldCurrency, relaywallet.FieldAvailableAmount, relaywallet.FieldFrozenAmount, relaywallet.FieldOverdraftLimit:
			values[i] = new(sql.NullString)
		case relaywallet.FieldCreatedAt, relaywallet.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelayWallet fields.
func (_m *RelayWallet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relaywallet.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case relaywallet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case relaywallet.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case relaywallet.FieldRelayKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field relay_key_id", values[i])
			} else if value.Valid {
				_m.RelayKeyID = int(value.Int64)
			}
		case relaywallet.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case relaywallet.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case relaywallet.FieldAvailableAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field available_amount", values[i])
			} else if value.Valid {
				_m.AvailableAmount = value.String
			}
		case relaywallet.FieldFrozenAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field frozen_amount", values[i])
			} else if value.Valid {
				_m.FrozenAmount = value.String
			}
		case relaywallet.FieldOverdraftLimit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overdraft_limit", values[i])
			} else if value.Valid {
				_m.OverdraftLimit = value.String
			}
		case relaywallet.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelayWallet.
// This includes values selected through modifiers, order, etc.
func (_m *RelayWallet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRelayKey queries the "relay_key" edge of the RelayWallet entity.
func (_m *RelayWallet) QueryRelayKey() *RelayKeyQuery {
	return NewRelayWalletClient(_m.config).QueryRelayKey(_m)
}

// Update returns a builder for updating this RelayWallet.
// Note that you need to call RelayWallet.Unwrap() before calling this method if this RelayWallet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelayWallet) Update() *RelayWalletUpdateOne {
	return NewRelayWalletClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelayWallet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelayWallet) Unwrap() *RelayWallet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelayWallet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelayWallet) String() string {
	var builder strings.Builder
	builder.WriteString("RelayWallet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("relay_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RelayKeyID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("available_amount=")
	builder.WriteString(_m.AvailableAmount)
	builder.WriteString(", ")
	builder.WriteString("frozen_amount=")
	builder.WriteString(_m.FrozenAmount)
	builder.WriteString(", ")
	builder.WriteString("overdraft_limit=")
	builder.WriteString(_m.OverdraftLimit)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// RelayWallets is a parsable slice of RelayWallet.
type RelayWallets []*RelayWallet
