// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/relaydailyusagesummary"
	"github.com/looplj/axonhub/internal/ent/relaykey"
	"github.com/looplj/axonhub/internal/ent/relayproduct"
	"github.com/looplj/axonhub/internal/ent/relaywallet"
	"github.com/looplj/axonhub/internal/ent/relaywalletledgerentry"
	"github.com/looplj/axonhub/internal/ent/user"
)

// RelayKeyQuery is the builder for querying RelayKey entities.
type RelayKeyQuery struct {
	config
	ctx                          *QueryContext
	order                        []relaykey.OrderOption
	inters                       []Interceptor
	predicates                   []predicate.RelayKey
	withAPIKey                   *APIKeyQuery
	withProject                  *ProjectQuery
	withProduct                  *RelayProductQuery
	withOwnerUser                *UserQuery
	withWallet                   *RelayWalletQuery
	withLedgerEntries            *RelayWalletLedgerEntryQuery
	withDailyUsageSummaries      *RelayDailyUsageSummaryQuery
	loadTotal                    []func(context.Context, []*RelayKey) error
	modifiers                    []func(*sql.Selector)
	withNamedLedgerEntries       map[string]*RelayWalletLedgerEntryQuery
	withNamedDailyUsageSummaries map[string]*RelayDailyUsageSummaryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RelayKeyQuery builder.
func (_q *RelayKeyQuery) Where(ps ...predicate.RelayKey) *RelayKeyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RelayKeyQuery) Limit(limit int) *RelayKeyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RelayKeyQuery) Offset(offset int) *RelayKeyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RelayKeyQuery) Unique(unique bool) *RelayKeyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RelayKeyQuery) Order(o ...relaykey.OrderOption) *RelayKeyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAPIKey chains the current query on the "api_key" edge.
func (_q *RelayKeyQuery) QueryAPIKey() *APIKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relaykey.Table, relaykey.FieldID, selector),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, relaykey.APIKeyTable, relaykey.APIKeyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProject chains the current query on the "project" edge.
func (_q *RelayKeyQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relaykey.Table, relaykey.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, relaykey.ProjectTable, relaykey.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProduct chains the current query on the "product" edge.
func (_q *RelayKeyQuery) QueryProduct() *RelayProductQuery {
	query := (&RelayProductClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relaykey.Table, relaykey.FieldID, selector),
			sqlgraph.To(relayproduct.Table, relayproduct.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, relaykey.ProductTable, relaykey.ProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOwnerUser chains the current query on the "owner_user" edge.
func (_q *RelayKeyQuery) QueryOwnerUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relaykey.Table, relaykey.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, relaykey.OwnerUserTable, relaykey.OwnerUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWallet chains the current query on the "wallet" edge.
func (_q *RelayKeyQuery) QueryWallet() *RelayWalletQuery {
	query := (&RelayWalletClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relaykey.Table, relaykey.FieldID, selector),
			sqlgraph.To(relaywallet.Table, relaywallet.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, relaykey.WalletTable, relaykey.WalletColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLedgerEntries chains the current query on the "ledger_entries" edge.
func (_q *RelayKeyQuery) QueryLedgerEntries() *RelayWalletLedgerEntryQuery {
	query := (&RelayWalletLedgerEntryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relaykey.Table, relaykey.FieldID, selector),
			sqlgraph.To(relaywalletledgerentry.Table, relaywalletledgerentry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, relaykey.LedgerEntriesTable, relaykey.LedgerEntriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDailyUsageSummaries chains the current query on the "daily_usage_summaries" edge.
func (_q *RelayKeyQuery) QueryDailyUsageSummaries() *RelayDailyUsageSummaryQuery {
	query := (&RelayDailyUsageSummaryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relaykey.Table, relaykey.FieldID, selector),
			sqlgraph.To(relaydailyusagesummary.Table, relaydailyusagesummary.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, relaykey.DailyUsageSummariesTable, relaykey.DailyUsageSummariesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RelayKey entity from the query.
// Returns a *NotFoundError when no RelayKey was found.
func (_q *RelayKeyQuery) First(ctx context.Context) (*RelayKey, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{relaykey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RelayKeyQuery) FirstX(ctx context.Context) *RelayKey {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RelayKey ID from the query.
// Returns a *NotFoundError when no RelayKey ID was found.
func (_q *RelayKeyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{relaykey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RelayKeyQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RelayKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RelayKey entity is found.
// Returns a *NotFoundError when no RelayKey entities are found.
func (_q *RelayKeyQuery) Only(ctx context.Context) (*RelayKey, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{relaykey.Label}
	default:
		return nil, &NotSingularError{relaykey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RelayKeyQuery) OnlyX(ctx context.Context) *RelayKey {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RelayKey ID in the query.
// Returns a *NotSingularError when more than one RelayKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RelayKeyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{relaykey.Label}
	default:
		err = &NotSingularError{relaykey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RelayKeyQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RelayKeys.
func (_q *RelayKeyQuery) All(ctx context.Context) ([]*RelayKey, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RelayKey, *RelayKeyQuery]()
	return withInterceptors[[]*RelayKey](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RelayKeyQuery) AllX(ctx context.Context) []*RelayKey {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RelayKey IDs.
func (_q *RelayKeyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(relaykey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RelayKeyQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RelayKeyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RelayKeyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RelayKeyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RelayKeyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RelayKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RelayKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RelayKeyQuery) Clone() *RelayKeyQuery {
	if _q == nil {
		return nil
	}
	return &RelayKeyQuery{
		config:                  _q.config,
		ctx:                     _q.ctx.Clone(),
		order:                   append([]relaykey.OrderOption{}, _q.order...),
		inters:                  append([]Interceptor{}, _q.inters...),
		predicates:              append([]predicate.RelayKey{}, _q.predicates...),
		withAPIKey:              _q.withAPIKey.Clone(),
		withProject:             _q.withProject.Clone(),
		withProduct:             _q.withProduct.Clone(),
		withOwnerUser:           _q.withOwnerUser.Clone(),
		withWallet:              _q.withWallet.Clone(),
		withLedgerEntries:       _q.withLedgerEntries.Clone(),
		withDailyUsageSummaries: _q.withDailyUsageSummaries.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithAPIKey tells the query-builder to eager-load the nodes that are connected to
// the "api_key" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelayKeyQuery) WithAPIKey(opts ...func(*APIKeyQuery)) *RelayKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAPIKey = query
	return _q
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelayKeyQuery) WithProject(opts ...func(*ProjectQuery)) *RelayKeyQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithProduct tells the query-builder to eager-load the nodes that are connected to
// the "product" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelayKeyQuery) WithProduct(opts ...func(*RelayProductQuery)) *RelayKeyQuery {
	query := (&RelayProductClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProduct = query
	return _q
}

// WithOwnerUser tells the query-builder to eager-load the nodes that are connected to
// the "owner_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelayKeyQuery) WithOwnerUser(opts ...func(*UserQuery)) *RelayKeyQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwnerUser = query
	return _q
}

// WithWallet tells the query-builder to eager-load the nodes that are connected to
// the "wallet" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelayKeyQuery) WithWallet(opts ...func(*RelayWalletQuery)) *RelayKeyQuery {
	query := (&RelayWalletClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWallet = query
	return _q
}

// WithLedgerEntries tells the query-builder to eager-load the nodes that are connected to
// the "ledger_entries" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelayKeyQuery) WithLedgerEntries(opts ...func(*RelayWalletLedgerEntryQuery)) *RelayKeyQuery {
	query := (&RelayWalletLedgerEntryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLedgerEntries = query
	return _q
}

// WithDailyUsageSummaries tells the query-builder to eager-load the nodes that are connected to
// the "daily_usage_summaries" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelayKeyQuery) WithDailyUsageSummaries(opts ...func(*RelayDailyUsageSummaryQuery)) *RelayKeyQuery {
	query := (&RelayDailyUsageSummaryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDailyUsageSummaries = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RelayKey.Query().
//		GroupBy(relaykey.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RelayKeyQuery) GroupBy(field string, fields ...string) *RelayKeyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RelayKeyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = relaykey.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.RelayKey.Query().
//		Select(relaykey.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *RelayKeyQuery) Select(fields ...string) *RelayKeySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RelayKeySelect{RelayKeyQuery: _q}
	sbuild.label = relaykey.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RelayKeySelect configured with the given aggregations.
func (_q *RelayKeyQuery) Aggregate(fns ...AggregateFunc) *RelayKeySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RelayKeyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !relaykey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if relaykey.Policy == nil {
		return errors.New("ent: uninitialized relaykey.Policy (forgotten import ent/runtime?)")
	}
	if err := relaykey.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *RelayKeyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RelayKey, error) {
	var (
		nodes       = []*RelayKey{}
		_spec       = _q.querySpec()
		loadedTypes = [7]bool{
			_q.withAPIKey != nil,
			_q.withProject != nil,
			_q.withProduct != nil,
			_q.withOwnerUser != nil,
			_q.withWallet != nil,
			_q.withLedgerEntries != nil,
			_q.withDailyUsageSummaries != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RelayKey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RelayKey{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAPIKey; query != nil {
		if err := _q.loadAPIKey(ctx, query, nodes, nil,
			func(n *RelayKey, e *APIKey) { n.Edges.APIKey = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *RelayKey, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProduct; query != nil {
		if err := _q.loadProduct(ctx, query, nodes, nil,
			func(n *RelayKey, e *RelayProduct) { n.Edges.Product = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOwnerUser; query != nil {
		if err := _q.loadOwnerUser(ctx, query, nodes, nil,
			func(n *RelayKey, e *User) { n.Edges.OwnerUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWallet; query != nil {
		if err := _q.loadWallet(ctx, query, nodes, nil,
			func(n *RelayKey, e *RelayWallet) { n.Edges.Wallet = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLedgerEntries; query != nil {
		if err := _q.loadLedgerEntries(ctx, query, nodes,
			func(n *RelayKey) { n.Edges.LedgerEntries = []*RelayWalletLedgerEntry{} },
			func(n *RelayKey, e *RelayWalletLedgerEntry) { n.Edges.LedgerEntries = append(n.Edges.LedgerEntries, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDailyUsageSummaries; query != nil {
		if err := _q.loadDailyUsageSummaries(ctx, query, nodes,
			func(n *RelayKey) { n.Edges.DailyUsageSummaries = []*RelayDailyUsageSummary{} },
			func(n *RelayKey, e *RelayDailyUsageSummary) {
				n.Edges.DailyUsageSummaries = append(n.Edges.DailyUsageSummaries, e)
			}); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedLedgerEntries {
		if err := _q.loadLedgerEntries(ctx, query, nodes,
			func(n *RelayKey) { n.appendNamedLedgerEntries(name) },
			func(n *RelayKey, e *RelayWalletLedgerEntry) { n.appendNamedLedgerEntries(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedDailyUsageSummaries {
		if err := _q.loadDailyUsageSummaries(ctx, query, nodes,
			func(n *RelayKey) { n.appendNamedDailyUsageSummaries(name) },
			func(n *RelayKey, e *RelayDailyUsageSummary) { n.appendNamedDailyUsageSummaries(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RelayKeyQuery) loadAPIKey(ctx context.Context, query *APIKeyQuery, nodes []*RelayKey, init func(*RelayKey), assign func(*RelayKey, *APIKey)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RelayKey)
	for i := range nodes {
		fk := nodes[i].APIKeyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(apikey.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "api_key_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RelayKeyQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*RelayKey, init func(*RelayKey), assign func(*RelayKey, *Project)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RelayKey)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RelayKeyQuery) loadProduct(ctx context.Context, query *RelayProductQuery, nodes []*RelayKey, init func(*RelayKey), assign func(*RelayKey, *RelayProduct)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RelayKey)
	for i := range nodes {
		fk := nodes[i].ProductID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(relayproduct.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "product_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RelayKeyQuery) loadOwnerUser(ctx context.Context, query *UserQuery, nodes []*RelayKey, init func(*RelayKey), assign func(*RelayKey, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RelayKey)
	for i := range nodes {
		if nodes[i].OwnerUserID == nil {
			continue
		}
		fk := *nodes[i].OwnerUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "owner_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RelayKeyQuery) loadWallet(ctx context.Context, query *RelayWalletQuery, nodes []*RelayKey, init func(*RelayKey), assign func(*RelayKey, *RelayWallet)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*RelayKey)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(relaywallet.FieldRelayKeyID)
	}
	query.Where(predicate.RelayWallet(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(relaykey.WalletColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RelayKeyID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "relay_key_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RelayKeyQuery) loadLedgerEntries(ctx context.Context, query *RelayWalletLedgerEntryQuery, nodes []*RelayKey, init func(*RelayKey), assign func(*RelayKey, *RelayWalletLedgerEntry)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*RelayKey)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(relaywalletledgerentry.FieldRelayKeyID)
	}
	query.Where(predicate.RelayWalletLedgerEntry(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(relaykey.LedgerEntriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RelayKeyID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "relay_key_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RelayKeyQuery) loadDailyUsageSummaries(ctx context.Context, query *RelayDailyUsageSummaryQuery, nodes []*RelayKey, init func(*RelayKey), assign func(*RelayKey, *RelayDailyUsageSummary)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*RelayKey)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(relaydailyusagesummary.FieldRelayKeyID)
	}
	query.Where(predicate.RelayDailyUsageSummary(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(relaykey.DailyUsageSummariesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RelayKeyID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "relay_key_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *RelayKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RelayKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(relaykey.Table, relaykey.Columns, sqlgraph.NewFieldSpec(relaykey.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relaykey.FieldID)
		for i := range fields {
			if fields[i] != relaykey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAPIKey != nil {
			_spec.Node.AddColumnOnce(relaykey.FieldAPIKeyID)
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(relaykey.FieldProjectID)
		}
		if _q.withProduct != nil {
			_spec.Node.AddColumnOnce(relaykey.FieldProductID)
		}
		if _q.withOwnerUser != nil {
			_spec.Node.AddColumnOnce(relaykey.FieldOwnerUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RelayKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(relaykey.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = relaykey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *RelayKeyQuery) Modify(modifiers ...func(s *sql.Selector)) *RelayKeySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// WithNamedLedgerEntries tells the query-builder to eager-load the nodes that are connected to the "ledger_entries"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *RelayKeyQuery) WithNamedLedgerEntries(name string, opts ...func(*RelayWalletLedgerEntryQuery)) *RelayKeyQuery {
	query := (&RelayWalletLedgerEntryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedLedgerEntries == nil {
		_q.withNamedLedgerEntries = make(map[string]*RelayWalletLedgerEntryQuery)
	}
	_q.withNamedLedgerEntries[name] = query
	return _q
}

// WithNamedDailyUsageSummaries tells the query-builder to eager-load the nodes that are connected to the "daily_usage_summaries"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *RelayKeyQuery) WithNamedDailyUsageSummaries(name string, opts ...func(*RelayDailyUsageSummaryQuery)) *RelayKeyQuery {
	query := (&RelayDailyUsageSummaryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedDailyUsageSummaries == nil {
		_q.withNamedDailyUsageSummaries = make(map[string]*RelayDailyUsageSummaryQuery)
	}
	_q.withNamedDailyUsageSummaries[name] = query
	return _q
}

// RelayKeyGroupBy is the group-by builder for RelayKey entities.
type RelayKeyGroupBy struct {
	selector
	build *RelayKeyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RelayKeyGroupBy) Aggregate(fns ...AggregateFunc) *RelayKeyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RelayKeyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RelayKeyQuery, *RelayKeyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RelayKeyGroupBy) sqlScan(ctx context.Context, root *RelayKeyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RelayKeySelect is the builder for selecting fields of RelayKey entities.
type RelayKeySelect struct {
	*RelayKeyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RelayKeySelect) Aggregate(fns ...AggregateFunc) *RelayKeySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RelayKeySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RelayKeyQuery, *RelayKeySelect](ctx, _s.RelayKeyQuery, _s, _s.inters, v)
}

func (_s *RelayKeySelect) sqlScan(ctx context.Context, root *RelayKeyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *RelayKeySelect) Modify(modifiers ...func(s *sql.Selector)) *RelayKeySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
