// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/userpointaccount"
)

// UserPointAccount is the model entity for the UserPointAccount schema.
type UserPointAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Owner user id for this point account
	UserID int `json:"user_id,omitempty"`
	// Spendable points stored as a decimal string
	AvailablePoints string `json:"available_points,omitempty"`
	// Pending points stored as a decimal string
	PendingPoints string `json:"pending_points,omitempty"`
	// Frozen points stored as a decimal string
	FrozenPoints string `json:"frozen_points,omitempty"`
	// Lifetime earned points stored as a decimal string
	LifetimeEarned string `json:"lifetime_earned,omitempty"`
	// Lifetime spent points stored as a decimal string
	LifetimeSpent string `json:"lifetime_spent,omitempty"`
	// Optimistic-lock version for point account updates
	Version      int64 `json:"version,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserPointAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userpointaccount.FieldID, userpointaccount.FieldUserID, userpointaccount.FieldVersion:
			values[i] = new(sql.NullInt64)
		case userpointaccount.FieldAvailablePoints, userpointaccount.FieldPendingPoints, userpointaccount.FieldFrozenPoints, userpointaccount.FieldLifetimeEarned, userpointaccount.FieldLifetimeSpent:
			values[i] = new(sql.NullString)
		case userpointaccount.FieldCreatedAt, userpointaccount.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserPointAccount fields.
func (_m *UserPointAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userpointaccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userpointaccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userpointaccount.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case userpointaccount.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case userpointaccount.FieldAvailablePoints:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field available_points", values[i])
			} else if value.Valid {
				_m.AvailablePoints = value.String
			}
		case userpointaccount.FieldPendingPoints:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pending_points", values[i])
			} else if value.Valid {
				_m.PendingPoints = value.String
			}
		case userpointaccount.FieldFrozenPoints:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field frozen_points", values[i])
			} else if value.Valid {
				_m.FrozenPoints = value.String
			}
		case userpointaccount.FieldLifetimeEarned:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lifetime_earned", values[i])
			} else if value.Valid {
				_m.LifetimeEarned = value.String
			}
		case userpointaccount.FieldLifetimeSpent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lifetime_spent", values[i])
			} else if value.Valid {
				_m.LifetimeSpent = value.String
			}
		case userpointaccount.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserPointAccount.
// This includes values selected through modifiers, order, etc.
func (_m *UserPointAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserPointAccount.
// Note that you need to call UserPointAccount.Unwrap() before calling this method if this UserPointAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserPointAccount) Update() *UserPointAccountUpdateOne {
	return NewUserPointAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserPointAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserPointAccount) Unwrap() *UserPointAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserPointAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserPointAccount) String() string {
	var builder strings.Builder
	builder.WriteString("UserPointAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("available_points=")
	builder.WriteString(_m.AvailablePoints)
	builder.WriteString(", ")
	builder.WriteString("pending_points=")
	builder.WriteString(_m.PendingPoints)
	builder.WriteString(", ")
	builder.WriteString("frozen_points=")
	builder.WriteString(_m.FrozenPoints)
	builder.WriteString(", ")
	builder.WriteString("lifetime_earned=")
	builder.WriteString(_m.LifetimeEarned)
	builder.WriteString(", ")
	builder.WriteString("lifetime_spent=")
	builder.WriteString(_m.LifetimeSpent)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// UserPointAccounts is a parsable slice of UserPointAccount.
type UserPointAccounts []*UserPointAccount
