// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/userpointledgerentry"
)

// UserPointLedgerEntryDelete is the builder for deleting a UserPointLedgerEntry entity.
type UserPointLedgerEntryDelete struct {
	config
	hooks    []Hook
	mutation *UserPointLedgerEntryMutation
}

// Where appends a list predicates to the UserPointLedgerEntryDelete builder.
func (_d *UserPointLedgerEntryDelete) Where(ps ...predicate.UserPointLedgerEntry) *UserPointLedgerEntryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserPointLedgerEntryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserPointLedgerEntryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserPointLedgerEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userpointledgerentry.Table, sqlgraph.NewFieldSpec(userpointledgerentry.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserPointLedgerEntryDeleteOne is the builder for deleting a single UserPointLedgerEntry entity.
type UserPointLedgerEntryDeleteOne struct {
	_d *UserPointLedgerEntryDelete
}

// Where appends a list predicates to the UserPointLedgerEntryDelete builder.
func (_d *UserPointLedgerEntryDeleteOne) Where(ps ...predicate.UserPointLedgerEntry) *UserPointLedgerEntryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserPointLedgerEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userpointledgerentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserPointLedgerEntryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
