// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/userpointaccount"
)

// UserPointAccountUpdate is the builder for updating UserPointAccount entities.
type UserPointAccountUpdate struct {
	config
	hooks     []Hook
	mutation  *UserPointAccountMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserPointAccountUpdate builder.
func (_u *UserPointAccountUpdate) Where(ps ...predicate.UserPointAccount) *UserPointAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserPointAccountUpdate) SetUpdatedAt(v time.Time) *UserPointAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAvailablePoints sets the "available_points" field.
func (_u *UserPointAccountUpdate) SetAvailablePoints(v string) *UserPointAccountUpdate {
	_u.mutation.SetAvailablePoints(v)
	return _u
}

// SetNillableAvailablePoints sets the "available_points" field if the given value is not nil.
func (_u *UserPointAccountUpdate) SetNillableAvailablePoints(v *string) *UserPointAccountUpdate {
	if v != nil {
		_u.SetAvailablePoints(*v)
	}
	return _u
}

// SetPendingPoints sets the "pending_points" field.
func (_u *UserPointAccountUpdate) SetPendingPoints(v string) *UserPointAccountUpdate {
	_u.mutation.SetPendingPoints(v)
	return _u
}

// SetNillablePendingPoints sets the "pending_points" field if the given value is not nil.
func (_u *UserPointAccountUpdate) SetNillablePendingPoints(v *string) *UserPointAccountUpdate {
	if v != nil {
		_u.SetPendingPoints(*v)
	}
	return _u
}

// SetFrozenPoints sets the "frozen_points" field.
func (_u *UserPointAccountUpdate) SetFrozenPoints(v string) *UserPointAccountUpdate {
	_u.mutation.SetFrozenPoints(v)
	return _u
}

// SetNillableFrozenPoints sets the "frozen_points" field if the given value is not nil.
func (_u *UserPointAccountUpdate) SetNillableFrozenPoints(v *string) *UserPointAccountUpdate {
	if v != nil {
		_u.SetFrozenPoints(*v)
	}
	return _u
}

// SetLifetimeEarned sets the "lifetime_earned" field.
func (_u *UserPointAccountUpdate) SetLifetimeEarned(v string) *UserPointAccountUpdate {
	_u.mutation.SetLifetimeEarned(v)
	return _u
}

// SetNillableLifetimeEarned sets the "lifetime_earned" field if the given value is not nil.
func (_u *UserPointAccountUpdate) SetNillableLifetimeEarned(v *string) *UserPointAccountUpdate {
	if v != nil {
		_u.SetLifetimeEarned(*v)
	}
	return _u
}

// SetLifetimeSpent sets the "lifetime_spent" field.
func (_u *UserPointAccountUpdate) SetLifetimeSpent(v string) *UserPointAccountUpdate {
	_u.mutation.SetLifetimeSpent(v)
	return _u
}

// SetNillableLifetimeSpent sets the "lifetime_spent" field if the given value is not nil.
func (_u *UserPointAccountUpdate) SetNillableLifetimeSpent(v *string) *UserPointAccountUpdate {
	if v != nil {
		_u.SetLifetimeSpent(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *UserPointAccountUpdate) SetVersion(v int64) *UserPointAccountUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *UserPointAccountUpdate) SetNillableVersion(v *int64) *UserPointAccountUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *UserPointAccountUpdate) AddVersion(v int64) *UserPointAccountUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the UserPointAccountMutation object of the builder.
func (_u *UserPointAccountUpdate) Mutation() *UserPointAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserPointAccountUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserPointAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserPointAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserPointAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserPointAccountUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if userpointaccount.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userpointaccount.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userpointaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserPointAccountUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserPointAccountUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserPointAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userpointaccount.Table, userpointaccount.Columns, sqlgraph.NewFieldSpec(userpointaccount.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userpointaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AvailablePoints(); ok {
		_spec.SetField(userpointaccount.FieldAvailablePoints, field.TypeString, value)
	}
	if value, ok := _u.mutation.PendingPoints(); ok {
		_spec.SetField(userpointaccount.FieldPendingPoints, field.TypeString, value)
	}
	if value, ok := _u.mutation.FrozenPoints(); ok {
		_spec.SetField(userpointaccount.FieldFrozenPoints, field.TypeString, value)
	}
	if value, ok := _u.mutation.LifetimeEarned(); ok {
		_spec.SetField(userpointaccount.FieldLifetimeEarned, field.TypeString, value)
	}
	if value, ok := _u.mutation.LifetimeSpent(); ok {
		_spec.SetField(userpointaccount.FieldLifetimeSpent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(userpointaccount.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(userpointaccount.FieldVersion, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userpointaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserPointAccountUpdateOne is the builder for updating a single UserPointAccount entity.
type UserPointAccountUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserPointAccountMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserPointAccountUpdateOne) SetUpdatedAt(v time.Time) *UserPointAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAvailablePoints sets the "available_points" field.
func (_u *UserPointAccountUpdateOne) SetAvailablePoints(v string) *UserPointAccountUpdateOne {
	_u.mutation.SetAvailablePoints(v)
	return _u
}

// SetNillableAvailablePoints sets the "available_points" field if the given value is not nil.
func (_u *UserPointAccountUpdateOne) SetNillableAvailablePoints(v *string) *UserPointAccountUpdateOne {
	if v != nil {
		_u.SetAvailablePoints(*v)
	}
	return _u
}

// SetPendingPoints sets the "pending_points" field.
func (_u *UserPointAccountUpdateOne) SetPendingPoints(v string) *UserPointAccountUpdateOne {
	_u.mutation.SetPendingPoints(v)
	return _u
}

// SetNillablePendingPoints sets the "pending_points" field if the given value is not nil.
func (_u *UserPointAccountUpdateOne) SetNillablePendingPoints(v *string) *UserPointAccountUpdateOne {
	if v != nil {
		_u.SetPendingPoints(*v)
	}
	return _u
}

// SetFrozenPoints sets the "frozen_points" field.
func (_u *UserPointAccountUpdateOne) SetFrozenPoints(v string) *UserPointAccountUpdateOne {
	_u.mutation.SetFrozenPoints(v)
	return _u
}

// SetNillableFrozenPoints sets the "frozen_points" field if the given value is not nil.
func (_u *UserPointAccountUpdateOne) SetNillableFrozenPoints(v *string) *UserPointAccountUpdateOne {
	if v != nil {
		_u.SetFrozenPoints(*v)
	}
	return _u
}

// SetLifetimeEarned sets the "lifetime_earned" field.
func (_u *UserPointAccountUpdateOne) SetLifetimeEarned(v string) *UserPointAccountUpdateOne {
	_u.mutation.SetLifetimeEarned(v)
	return _u
}

// SetNillableLifetimeEarned sets the "lifetime_earned" field if the given value is not nil.
func (_u *UserPointAccountUpdateOne) SetNillableLifetimeEarned(v *string) *UserPointAccountUpdateOne {
	if v != nil {
		_u.SetLifetimeEarned(*v)
	}
	return _u
}

// SetLifetimeSpent sets the "lifetime_spent" field.
func (_u *UserPointAccountUpdateOne) SetLifetimeSpent(v string) *UserPointAccountUpdateOne {
	_u.mutation.SetLifetimeSpent(v)
	return _u
}

// SetNillableLifetimeSpent sets the "lifetime_spent" field if the given value is not nil.
func (_u *UserPointAccountUpdateOne) SetNillableLifetimeSpent(v *string) *UserPointAccountUpdateOne {
	if v != nil {
		_u.SetLifetimeSpent(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *UserPointAccountUpdateOne) SetVersion(v int64) *UserPointAccountUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *UserPointAccountUpdateOne) SetNillableVersion(v *int64) *UserPointAccountUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *UserPointAccountUpdateOne) AddVersion(v int64) *UserPointAccountUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the UserPointAccountMutation object of the builder.
func (_u *UserPointAccountUpdateOne) Mutation() *UserPointAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserPointAccountUpdate builder.
func (_u *UserPointAccountUpdateOne) Where(ps ...predicate.UserPointAccount) *UserPointAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserPointAccountUpdateOne) Select(field string, fields ...string) *UserPointAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserPointAccount entity.
func (_u *UserPointAccountUpdateOne) Save(ctx context.Context) (*UserPointAccount, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserPointAccountUpdateOne) SaveX(ctx context.Context) *UserPointAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserPointAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserPointAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserPointAccountUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if userpointaccount.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userpointaccount.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userpointaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserPointAccountUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserPointAccountUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserPointAccountUpdateOne) sqlSave(ctx context.Context) (_node *UserPointAccount, err error) {
	_spec := sqlgraph.NewUpdateSpec(userpointaccount.Table, userpointaccount.Columns, sqlgraph.NewFieldSpec(userpointaccount.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserPointAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userpointaccount.FieldID)
		for _, f := range fields {
			if !userpointaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userpointaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userpointaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AvailablePoints(); ok {
		_spec.SetField(userpointaccount.FieldAvailablePoints, field.TypeString, value)
	}
	if value, ok := _u.mutation.PendingPoints(); ok {
		_spec.SetField(userpointaccount.FieldPendingPoints, field.TypeString, value)
	}
	if value, ok := _u.mutation.FrozenPoints(); ok {
		_spec.SetField(userpointaccount.FieldFrozenPoints, field.TypeString, value)
	}
	if value, ok := _u.mutation.LifetimeEarned(); ok {
		_spec.SetField(userpointaccount.FieldLifetimeEarned, field.TypeString, value)
	}
	if value, ok := _u.mutation.LifetimeSpent(); ok {
		_spec.SetField(userpointaccount.FieldLifetimeSpent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(userpointaccount.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(userpointaccount.FieldVersion, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UserPointAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userpointaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
