// Code generated by ent, DO NOT EDIT.

package relaydailyusagesummary

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldUpdatedAt, v))
}

// RelayKeyID applies equality check predicate on the "relay_key_id" field. It's identical to RelayKeyIDEQ.
func RelayKeyID(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldRelayKeyID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldProjectID, v))
}

// StatDate applies equality check predicate on the "stat_date" field. It's identical to StatDateEQ.
func StatDate(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldStatDate, v))
}

// RequestCount applies equality check predicate on the "request_count" field. It's identical to RequestCountEQ.
func RequestCount(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldRequestCount, v))
}

// TotalTokens applies equality check predicate on the "total_tokens" field. It's identical to TotalTokensEQ.
func TotalTokens(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalCharge applies equality check predicate on the "total_charge" field. It's identical to TotalChargeEQ.
func TotalCharge(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldTotalCharge, v))
}

// TotalUpstreamCost applies equality check predicate on the "total_upstream_cost" field. It's identical to TotalUpstreamCostEQ.
func TotalUpstreamCost(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldTotalUpstreamCost, v))
}

// LastRequestID applies equality check predicate on the "last_request_id" field. It's identical to LastRequestIDEQ.
func LastRequestID(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldLastRequestID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLTE(FieldUpdatedAt, v))
}

// RelayKeyIDEQ applies the EQ predicate on the "relay_key_id" field.
func RelayKeyIDEQ(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldRelayKeyID, v))
}

// RelayKeyIDNEQ applies the NEQ predicate on the "relay_key_id" field.
func RelayKeyIDNEQ(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNEQ(FieldRelayKeyID, v))
}

// RelayKeyIDIn applies the In predicate on the "relay_key_id" field.
func RelayKeyIDIn(vs ...int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldIn(FieldRelayKeyID, vs...))
}

// RelayKeyIDNotIn applies the NotIn predicate on the "relay_key_id" field.
func RelayKeyIDNotIn(vs ...int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNotIn(FieldRelayKeyID, vs...))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLTE(FieldProjectID, v))
}

// StatDateEQ applies the EQ predicate on the "stat_date" field.
func StatDateEQ(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldStatDate, v))
}

// StatDateNEQ applies the NEQ predicate on the "stat_date" field.
func StatDateNEQ(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNEQ(FieldStatDate, v))
}

// StatDateIn applies the In predicate on the "stat_date" field.
func StatDateIn(vs ...time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldIn(FieldStatDate, vs...))
}

// StatDateNotIn applies the NotIn predicate on the "stat_date" field.
func StatDateNotIn(vs ...time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNotIn(FieldStatDate, vs...))
}

// StatDateGT applies the GT predicate on the "stat_date" field.
func StatDateGT(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGT(FieldStatDate, v))
}

// StatDateGTE applies the GTE predicate on the "stat_date" field.
func StatDateGTE(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGTE(FieldStatDate, v))
}

// StatDateLT applies the LT predicate on the "stat_date" field.
func StatDateLT(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLT(FieldStatDate, v))
}

// StatDateLTE applies the LTE predicate on the "stat_date" field.
func StatDateLTE(v time.Time) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLTE(FieldStatDate, v))
}

// RequestCountEQ applies the EQ predicate on the "request_count" field.
func RequestCountEQ(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldRequestCount, v))
}

// RequestCountNEQ applies the NEQ predicate on the "request_count" field.
func RequestCountNEQ(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNEQ(FieldRequestCount, v))
}

// RequestCountIn applies the In predicate on the "request_count" field.
func RequestCountIn(vs ...int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldIn(FieldRequestCount, vs...))
}

// RequestCountNotIn applies the NotIn predicate on the "request_count" field.
func RequestCountNotIn(vs ...int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNotIn(FieldRequestCount, vs...))
}

// RequestCountGT applies the GT predicate on the "request_count" field.
func RequestCountGT(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGT(FieldRequestCount, v))
}

// RequestCountGTE applies the GTE predicate on the "request_count" field.
func RequestCountGTE(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGTE(FieldRequestCount, v))
}

// RequestCountLT applies the LT predicate on the "request_count" field.
func RequestCountLT(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLT(FieldRequestCount, v))
}

// RequestCountLTE applies the LTE predicate on the "request_count" field.
func RequestCountLTE(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLTE(FieldRequestCount, v))
}

// TotalTokensEQ applies the EQ predicate on the "total_tokens" field.
func TotalTokensEQ(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalTokensNEQ applies the NEQ predicate on the "total_tokens" field.
func TotalTokensNEQ(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNEQ(FieldTotalTokens, v))
}

// TotalTokensIn applies the In predicate on the "total_tokens" field.
func TotalTokensIn(vs ...int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldIn(FieldTotalTokens, vs...))
}

// TotalTokensNotIn applies the NotIn predicate on the "total_tokens" field.
func TotalTokensNotIn(vs ...int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNotIn(FieldTotalTokens, vs...))
}

// TotalTokensGT applies the GT predicate on the "total_tokens" field.
func TotalTokensGT(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGT(FieldTotalTokens, v))
}

// TotalTokensGTE applies the GTE predicate on the "total_tokens" field.
func TotalTokensGTE(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGTE(FieldTotalTokens, v))
}

// TotalTokensLT applies the LT predicate on the "total_tokens" field.
func TotalTokensLT(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLT(FieldTotalTokens, v))
}

// TotalTokensLTE applies the LTE predicate on the "total_tokens" field.
func TotalTokensLTE(v int64) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLTE(FieldTotalTokens, v))
}

// TotalChargeEQ applies the EQ predicate on the "total_charge" field.
func TotalChargeEQ(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldTotalCharge, v))
}

// TotalChargeNEQ applies the NEQ predicate on the "total_charge" field.
func TotalChargeNEQ(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNEQ(FieldTotalCharge, v))
}

// TotalChargeIn applies the In predicate on the "total_charge" field.
func TotalChargeIn(vs ...string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldIn(FieldTotalCharge, vs...))
}

// TotalChargeNotIn applies the NotIn predicate on the "total_charge" field.
func TotalChargeNotIn(vs ...string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNotIn(FieldTotalCharge, vs...))
}

// TotalChargeGT applies the GT predicate on the "total_charge" field.
func TotalChargeGT(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGT(FieldTotalCharge, v))
}

// TotalChargeGTE applies the GTE predicate on the "total_charge" field.
func TotalChargeGTE(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGTE(FieldTotalCharge, v))
}

// TotalChargeLT applies the LT predicate on the "total_charge" field.
func TotalChargeLT(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLT(FieldTotalCharge, v))
}

// TotalChargeLTE applies the LTE predicate on the "total_charge" field.
func TotalChargeLTE(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLTE(FieldTotalCharge, v))
}

// TotalChargeContains applies the Contains predicate on the "total_charge" field.
func TotalChargeContains(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldContains(FieldTotalCharge, v))
}

// TotalChargeHasPrefix applies the HasPrefix predicate on the "total_charge" field.
func TotalChargeHasPrefix(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldHasPrefix(FieldTotalCharge, v))
}

// TotalChargeHasSuffix applies the HasSuffix predicate on the "total_charge" field.
func TotalChargeHasSuffix(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldHasSuffix(FieldTotalCharge, v))
}

// TotalChargeEqualFold applies the EqualFold predicate on the "total_charge" field.
func TotalChargeEqualFold(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEqualFold(FieldTotalCharge, v))
}

// TotalChargeContainsFold applies the ContainsFold predicate on the "total_charge" field.
func TotalChargeContainsFold(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldContainsFold(FieldTotalCharge, v))
}

// TotalUpstreamCostEQ applies the EQ predicate on the "total_upstream_cost" field.
func TotalUpstreamCostEQ(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldTotalUpstreamCost, v))
}

// TotalUpstreamCostNEQ applies the NEQ predicate on the "total_upstream_cost" field.
func TotalUpstreamCostNEQ(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNEQ(FieldTotalUpstreamCost, v))
}

// TotalUpstreamCostIn applies the In predicate on the "total_upstream_cost" field.
func TotalUpstreamCostIn(vs ...string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldIn(FieldTotalUpstreamCost, vs...))
}

// TotalUpstreamCostNotIn applies the NotIn predicate on the "total_upstream_cost" field.
func TotalUpstreamCostNotIn(vs ...string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNotIn(FieldTotalUpstreamCost, vs...))
}

// TotalUpstreamCostGT applies the GT predicate on the "total_upstream_cost" field.
func TotalUpstreamCostGT(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGT(FieldTotalUpstreamCost, v))
}

// TotalUpstreamCostGTE applies the GTE predicate on the "total_upstream_cost" field.
func TotalUpstreamCostGTE(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGTE(FieldTotalUpstreamCost, v))
}

// TotalUpstreamCostLT applies the LT predicate on the "total_upstream_cost" field.
func TotalUpstreamCostLT(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLT(FieldTotalUpstreamCost, v))
}

// TotalUpstreamCostLTE applies the LTE predicate on the "total_upstream_cost" field.
func TotalUpstreamCostLTE(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLTE(FieldTotalUpstreamCost, v))
}

// TotalUpstreamCostContains applies the Contains predicate on the "total_upstream_cost" field.
func TotalUpstreamCostContains(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldContains(FieldTotalUpstreamCost, v))
}

// TotalUpstreamCostHasPrefix applies the HasPrefix predicate on the "total_upstream_cost" field.
func TotalUpstreamCostHasPrefix(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldHasPrefix(FieldTotalUpstreamCost, v))
}

// TotalUpstreamCostHasSuffix applies the HasSuffix predicate on the "total_upstream_cost" field.
func TotalUpstreamCostHasSuffix(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldHasSuffix(FieldTotalUpstreamCost, v))
}

// TotalUpstreamCostEqualFold applies the EqualFold predicate on the "total_upstream_cost" field.
func TotalUpstreamCostEqualFold(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEqualFold(FieldTotalUpstreamCost, v))
}

// TotalUpstreamCostContainsFold applies the ContainsFold predicate on the "total_upstream_cost" field.
func TotalUpstreamCostContainsFold(v string) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldContainsFold(FieldTotalUpstreamCost, v))
}

// LastRequestIDEQ applies the EQ predicate on the "last_request_id" field.
func LastRequestIDEQ(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldEQ(FieldLastRequestID, v))
}

// LastRequestIDNEQ applies the NEQ predicate on the "last_request_id" field.
func LastRequestIDNEQ(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNEQ(FieldLastRequestID, v))
}

// LastRequestIDIn applies the In predicate on the "last_request_id" field.
func LastRequestIDIn(vs ...int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldIn(FieldLastRequestID, vs...))
}

// LastRequestIDNotIn applies the NotIn predicate on the "last_request_id" field.
func LastRequestIDNotIn(vs ...int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNotIn(FieldLastRequestID, vs...))
}

// LastRequestIDGT applies the GT predicate on the "last_request_id" field.
func LastRequestIDGT(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGT(FieldLastRequestID, v))
}

// LastRequestIDGTE applies the GTE predicate on the "last_request_id" field.
func LastRequestIDGTE(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldGTE(FieldLastRequestID, v))
}

// LastRequestIDLT applies the LT predicate on the "last_request_id" field.
func LastRequestIDLT(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLT(FieldLastRequestID, v))
}

// LastRequestIDLTE applies the LTE predicate on the "last_request_id" field.
func LastRequestIDLTE(v int) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldLTE(FieldLastRequestID, v))
}

// LastRequestIDIsNil applies the IsNil predicate on the "last_request_id" field.
func LastRequestIDIsNil() predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldIsNull(FieldLastRequestID))
}

// LastRequestIDNotNil applies the NotNil predicate on the "last_request_id" field.
func LastRequestIDNotNil() predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.FieldNotNull(FieldLastRequestID))
}

// HasRelayKey applies the HasEdge predicate on the "relay_key" edge.
func HasRelayKey() predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RelayKeyTable, RelayKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelayKeyWith applies the HasEdge predicate on the "relay_key" edge with a given conditions (other predicates).
func HasRelayKeyWith(preds ...predicate.RelayKey) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(func(s *sql.Selector) {
		step := newRelayKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelayDailyUsageSummary) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelayDailyUsageSummary) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelayDailyUsageSummary) predicate.RelayDailyUsageSummary {
	return predicate.RelayDailyUsageSummary(sql.NotPredicates(p))
}
