// Code generated by ent, DO NOT EDIT.

package userpointledgerentry

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the userpointledgerentry type in the database.
	Label = "user_point_ledger_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDirection holds the string denoting the direction field in the database.
	FieldDirection = "direction"
	// FieldScene holds the string denoting the scene field in the database.
	FieldScene = "scene"
	// FieldPoints holds the string denoting the points field in the database.
	FieldPoints = "points"
	// FieldBalanceBefore holds the string denoting the balance_before field in the database.
	FieldBalanceBefore = "balance_before"
	// FieldBalanceAfter holds the string denoting the balance_after field in the database.
	FieldBalanceAfter = "balance_after"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldRelatedChannelID holds the string denoting the related_channel_id field in the database.
	FieldRelatedChannelID = "related_channel_id"
	// FieldRelatedRequestID holds the string denoting the related_request_id field in the database.
	FieldRelatedRequestID = "related_request_id"
	// FieldRelatedUsageLogID holds the string denoting the related_usage_log_id field in the database.
	FieldRelatedUsageLogID = "related_usage_log_id"
	// FieldRelatedAPIKeyID holds the string denoting the related_api_key_id field in the database.
	FieldRelatedAPIKeyID = "related_api_key_id"
	// FieldRelatedProjectID holds the string denoting the related_project_id field in the database.
	FieldRelatedProjectID = "related_project_id"
	// FieldConversionRateSnapshot holds the string denoting the conversion_rate_snapshot field in the database.
	FieldConversionRateSnapshot = "conversion_rate_snapshot"
	// FieldSettlementStatus holds the string denoting the settlement_status field in the database.
	FieldSettlementStatus = "settlement_status"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// Table holds the table name of the userpointledgerentry in the database.
	Table = "user_point_ledger_entries"
)

// Columns holds all SQL columns for userpointledgerentry fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldDirection,
	FieldScene,
	FieldPoints,
	FieldBalanceBefore,
	FieldBalanceAfter,
	FieldIdempotencyKey,
	FieldRelatedChannelID,
	FieldRelatedRequestID,
	FieldRelatedUsageLogID,
	FieldRelatedAPIKeyID,
	FieldRelatedProjectID,
	FieldConversionRateSnapshot,
	FieldSettlementStatus,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Direction defines the type for the "direction" enum field.
type Direction string

// Direction values.
const (
	DirectionCredit Direction = "credit"
	DirectionDebit  Direction = "debit"
)

func (d Direction) String() string {
	return string(d)
}

// DirectionValidator is a validator for the "direction" field enum values. It is called by the builders before save.
func DirectionValidator(d Direction) error {
	switch d {
	case DirectionCredit, DirectionDebit:
		return nil
	default:
		return fmt.Errorf("userpointledgerentry: invalid enum value for direction field: %q", d)
	}
}

// Scene defines the type for the "scene" enum field.
type Scene string

// Scene values.
const (
	SceneContributionPending Scene = "contribution_pending"
	SceneContributionReward  Scene = "contribution_reward"
	SceneConsume             Scene = "consume"
	SceneAdjustment          Scene = "adjustment"
)

func (s Scene) String() string {
	return string(s)
}

// SceneValidator is a validator for the "scene" field enum values. It is called by the builders before save.
func SceneValidator(s Scene) error {
	switch s {
	case SceneContributionPending, SceneContributionReward, SceneConsume, SceneAdjustment:
		return nil
	default:
		return fmt.Errorf("userpointledgerentry: invalid enum value for scene field: %q", s)
	}
}

// SettlementStatus defines the type for the "settlement_status" enum field.
type SettlementStatus string

// SettlementStatusPosted is the default value of the SettlementStatus enum.
const DefaultSettlementStatus = SettlementStatusPosted

// SettlementStatus values.
const (
	SettlementStatusPosted SettlementStatus = "posted"
)

func (ss SettlementStatus) String() string {
	return string(ss)
}

// SettlementStatusValidator is a validator for the "settlement_status" field enum values. It is called by the builders before save.
func SettlementStatusValidator(ss SettlementStatus) error {
	switch ss {
	case SettlementStatusPosted:
		return nil
	default:
		return fmt.Errorf("userpointledgerentry: invalid enum value for settlement_status field: %q", ss)
	}
}

// OrderOption defines the ordering options for the UserPointLedgerEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByDirection orders the results by the direction field.
func ByDirection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirection, opts...).ToFunc()
}

// ByScene orders the results by the scene field.
func ByScene(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScene, opts...).ToFunc()
}

// ByPoints orders the results by the points field.
func ByPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoints, opts...).ToFunc()
}

// ByBalanceBefore orders the results by the balance_before field.
func ByBalanceBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceBefore, opts...).ToFunc()
}

// ByBalanceAfter orders the results by the balance_after field.
func ByBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfter, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByRelatedChannelID orders the results by the related_channel_id field.
func ByRelatedChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelatedChannelID, opts...).ToFunc()
}

// ByRelatedRequestID orders the results by the related_request_id field.
func ByRelatedRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelatedRequestID, opts...).ToFunc()
}

// ByRelatedUsageLogID orders the results by the related_usage_log_id field.
func ByRelatedUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelatedUsageLogID, opts...).ToFunc()
}

// ByRelatedAPIKeyID orders the results by the related_api_key_id field.
func ByRelatedAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelatedAPIKeyID, opts...).ToFunc()
}

// ByRelatedProjectID orders the results by the related_project_id field.
func ByRelatedProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelatedProjectID, opts...).ToFunc()
}

// ByConversionRateSnapshot orders the results by the conversion_rate_snapshot field.
func ByConversionRateSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConversionRateSnapshot, opts...).ToFunc()
}

// BySettlementStatus orders the results by the settlement_status field.
func BySettlementStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementStatus, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Direction) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Direction) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Direction(str)
	if err := DirectionValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Direction", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Scene) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Scene) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Scene(str)
	if err := SceneValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Scene", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e SettlementStatus) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *SettlementStatus) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = SettlementStatus(str)
	if err := SettlementStatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid SettlementStatus", str)
	}
	return nil
}
