// Code generated by ent, DO NOT EDIT.

package userpointledgerentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldUserID, v))
}

// Points applies equality check predicate on the "points" field. It's identical to PointsEQ.
func Points(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldPoints, v))
}

// BalanceBefore applies equality check predicate on the "balance_before" field. It's identical to BalanceBeforeEQ.
func BalanceBefore(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldBalanceAfter, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldIdempotencyKey, v))
}

// RelatedChannelID applies equality check predicate on the "related_channel_id" field. It's identical to RelatedChannelIDEQ.
func RelatedChannelID(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldRelatedChannelID, v))
}

// RelatedRequestID applies equality check predicate on the "related_request_id" field. It's identical to RelatedRequestIDEQ.
func RelatedRequestID(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldRelatedRequestID, v))
}

// RelatedUsageLogID applies equality check predicate on the "related_usage_log_id" field. It's identical to RelatedUsageLogIDEQ.
func RelatedUsageLogID(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldRelatedUsageLogID, v))
}

// RelatedAPIKeyID applies equality check predicate on the "related_api_key_id" field. It's identical to RelatedAPIKeyIDEQ.
func RelatedAPIKeyID(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldRelatedAPIKeyID, v))
}

// RelatedProjectID applies equality check predicate on the "related_project_id" field. It's identical to RelatedProjectIDEQ.
func RelatedProjectID(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldRelatedProjectID, v))
}

// ConversionRateSnapshot applies equality check predicate on the "conversion_rate_snapshot" field. It's identical to ConversionRateSnapshotEQ.
func ConversionRateSnapshot(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldConversionRateSnapshot, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldUserID, v))
}

// DirectionEQ applies the EQ predicate on the "direction" field.
func DirectionEQ(v Direction) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldDirection, v))
}

// DirectionNEQ applies the NEQ predicate on the "direction" field.
func DirectionNEQ(v Direction) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldDirection, v))
}

// DirectionIn applies the In predicate on the "direction" field.
func DirectionIn(vs ...Direction) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldDirection, vs...))
}

// DirectionNotIn applies the NotIn predicate on the "direction" field.
func DirectionNotIn(vs ...Direction) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldDirection, vs...))
}

// SceneEQ applies the EQ predicate on the "scene" field.
func SceneEQ(v Scene) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldScene, v))
}

// SceneNEQ applies the NEQ predicate on the "scene" field.
func SceneNEQ(v Scene) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldScene, v))
}

// SceneIn applies the In predicate on the "scene" field.
func SceneIn(vs ...Scene) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldScene, vs...))
}

// SceneNotIn applies the NotIn predicate on the "scene" field.
func SceneNotIn(vs ...Scene) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldScene, vs...))
}

// PointsEQ applies the EQ predicate on the "points" field.
func PointsEQ(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldPoints, v))
}

// PointsNEQ applies the NEQ predicate on the "points" field.
func PointsNEQ(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldPoints, v))
}

// PointsIn applies the In predicate on the "points" field.
func PointsIn(vs ...string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldPoints, vs...))
}

// PointsNotIn applies the NotIn predicate on the "points" field.
func PointsNotIn(vs ...string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldPoints, vs...))
}

// PointsGT applies the GT predicate on the "points" field.
func PointsGT(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldPoints, v))
}

// PointsGTE applies the GTE predicate on the "points" field.
func PointsGTE(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldPoints, v))
}

// PointsLT applies the LT predicate on the "points" field.
func PointsLT(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldPoints, v))
}

// PointsLTE applies the LTE predicate on the "points" field.
func PointsLTE(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldPoints, v))
}

// PointsContains applies the Contains predicate on the "points" field.
func PointsContains(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldContains(FieldPoints, v))
}

// PointsHasPrefix applies the HasPrefix predicate on the "points" field.
func PointsHasPrefix(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldHasPrefix(FieldPoints, v))
}

// PointsHasSuffix applies the HasSuffix predicate on the "points" field.
func PointsHasSuffix(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldHasSuffix(FieldPoints, v))
}

// PointsEqualFold applies the EqualFold predicate on the "points" field.
func PointsEqualFold(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEqualFold(FieldPoints, v))
}

// PointsContainsFold applies the ContainsFold predicate on the "points" field.
func PointsContainsFold(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldContainsFold(FieldPoints, v))
}

// BalanceBeforeEQ applies the EQ predicate on the "balance_before" field.
func BalanceBeforeEQ(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceBeforeNEQ applies the NEQ predicate on the "balance_before" field.
func BalanceBeforeNEQ(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldBalanceBefore, v))
}

// BalanceBeforeIn applies the In predicate on the "balance_before" field.
func BalanceBeforeIn(vs ...string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeNotIn applies the NotIn predicate on the "balance_before" field.
func BalanceBeforeNotIn(vs ...string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeGT applies the GT predicate on the "balance_before" field.
func BalanceBeforeGT(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldBalanceBefore, v))
}

// BalanceBeforeGTE applies the GTE predicate on the "balance_before" field.
func BalanceBeforeGTE(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldBalanceBefore, v))
}

// BalanceBeforeLT applies the LT predicate on the "balance_before" field.
func BalanceBeforeLT(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldBalanceBefore, v))
}

// BalanceBeforeLTE applies the LTE predicate on the "balance_before" field.
func BalanceBeforeLTE(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldBalanceBefore, v))
}

// BalanceBeforeContains applies the Contains predicate on the "balance_before" field.
func BalanceBeforeContains(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldContains(FieldBalanceBefore, v))
}

// BalanceBeforeHasPrefix applies the HasPrefix predicate on the "balance_before" field.
func BalanceBeforeHasPrefix(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldHasPrefix(FieldBalanceBefore, v))
}

// BalanceBeforeHasSuffix applies the HasSuffix predicate on the "balance_before" field.
func BalanceBeforeHasSuffix(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldHasSuffix(FieldBalanceBefore, v))
}

// BalanceBeforeEqualFold applies the EqualFold predicate on the "balance_before" field.
func BalanceBeforeEqualFold(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEqualFold(FieldBalanceBefore, v))
}

// BalanceBeforeContainsFold applies the ContainsFold predicate on the "balance_before" field.
func BalanceBeforeContainsFold(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldContainsFold(FieldBalanceBefore, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldBalanceAfter, v))
}

// BalanceAfterContains applies the Contains predicate on the "balance_after" field.
func BalanceAfterContains(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldContains(FieldBalanceAfter, v))
}

// BalanceAfterHasPrefix applies the HasPrefix predicate on the "balance_after" field.
func BalanceAfterHasPrefix(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldHasPrefix(FieldBalanceAfter, v))
}

// BalanceAfterHasSuffix applies the HasSuffix predicate on the "balance_after" field.
func BalanceAfterHasSuffix(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldHasSuffix(FieldBalanceAfter, v))
}

// BalanceAfterEqualFold applies the EqualFold predicate on the "balance_after" field.
func BalanceAfterEqualFold(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEqualFold(FieldBalanceAfter, v))
}

// BalanceAfterContainsFold applies the ContainsFold predicate on the "balance_after" field.
func BalanceAfterContainsFold(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldContainsFold(FieldBalanceAfter, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// RelatedChannelIDEQ applies the EQ predicate on the "related_channel_id" field.
func RelatedChannelIDEQ(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldRelatedChannelID, v))
}

// RelatedChannelIDNEQ applies the NEQ predicate on the "related_channel_id" field.
func RelatedChannelIDNEQ(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldRelatedChannelID, v))
}

// RelatedChannelIDIn applies the In predicate on the "related_channel_id" field.
func RelatedChannelIDIn(vs ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldRelatedChannelID, vs...))
}

// RelatedChannelIDNotIn applies the NotIn predicate on the "related_channel_id" field.
func RelatedChannelIDNotIn(vs ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldRelatedChannelID, vs...))
}

// RelatedChannelIDGT applies the GT predicate on the "related_channel_id" field.
func RelatedChannelIDGT(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldRelatedChannelID, v))
}

// RelatedChannelIDGTE applies the GTE predicate on the "related_channel_id" field.
func RelatedChannelIDGTE(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldRelatedChannelID, v))
}

// RelatedChannelIDLT applies the LT predicate on the "related_channel_id" field.
func RelatedChannelIDLT(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldRelatedChannelID, v))
}

// RelatedChannelIDLTE applies the LTE predicate on the "related_channel_id" field.
func RelatedChannelIDLTE(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldRelatedChannelID, v))
}

// RelatedChannelIDIsNil applies the IsNil predicate on the "related_channel_id" field.
func RelatedChannelIDIsNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIsNull(FieldRelatedChannelID))
}

// RelatedChannelIDNotNil applies the NotNil predicate on the "related_channel_id" field.
func RelatedChannelIDNotNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotNull(FieldRelatedChannelID))
}

// RelatedRequestIDEQ applies the EQ predicate on the "related_request_id" field.
func RelatedRequestIDEQ(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldRelatedRequestID, v))
}

// RelatedRequestIDNEQ applies the NEQ predicate on the "related_request_id" field.
func RelatedRequestIDNEQ(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldRelatedRequestID, v))
}

// RelatedRequestIDIn applies the In predicate on the "related_request_id" field.
func RelatedRequestIDIn(vs ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldRelatedRequestID, vs...))
}

// RelatedRequestIDNotIn applies the NotIn predicate on the "related_request_id" field.
func RelatedRequestIDNotIn(vs ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldRelatedRequestID, vs...))
}

// RelatedRequestIDGT applies the GT predicate on the "related_request_id" field.
func RelatedRequestIDGT(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldRelatedRequestID, v))
}

// RelatedRequestIDGTE applies the GTE predicate on the "related_request_id" field.
func RelatedRequestIDGTE(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldRelatedRequestID, v))
}

// RelatedRequestIDLT applies the LT predicate on the "related_request_id" field.
func RelatedRequestIDLT(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldRelatedRequestID, v))
}

// RelatedRequestIDLTE applies the LTE predicate on the "related_request_id" field.
func RelatedRequestIDLTE(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldRelatedRequestID, v))
}

// RelatedRequestIDIsNil applies the IsNil predicate on the "related_request_id" field.
func RelatedRequestIDIsNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIsNull(FieldRelatedRequestID))
}

// RelatedRequestIDNotNil applies the NotNil predicate on the "related_request_id" field.
func RelatedRequestIDNotNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotNull(FieldRelatedRequestID))
}

// RelatedUsageLogIDEQ applies the EQ predicate on the "related_usage_log_id" field.
func RelatedUsageLogIDEQ(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldRelatedUsageLogID, v))
}

// RelatedUsageLogIDNEQ applies the NEQ predicate on the "related_usage_log_id" field.
func RelatedUsageLogIDNEQ(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldRelatedUsageLogID, v))
}

// RelatedUsageLogIDIn applies the In predicate on the "related_usage_log_id" field.
func RelatedUsageLogIDIn(vs ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldRelatedUsageLogID, vs...))
}

// RelatedUsageLogIDNotIn applies the NotIn predicate on the "related_usage_log_id" field.
func RelatedUsageLogIDNotIn(vs ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldRelatedUsageLogID, vs...))
}

// RelatedUsageLogIDGT applies the GT predicate on the "related_usage_log_id" field.
func RelatedUsageLogIDGT(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldRelatedUsageLogID, v))
}

// RelatedUsageLogIDGTE applies the GTE predicate on the "related_usage_log_id" field.
func RelatedUsageLogIDGTE(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldRelatedUsageLogID, v))
}

// RelatedUsageLogIDLT applies the LT predicate on the "related_usage_log_id" field.
func RelatedUsageLogIDLT(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldRelatedUsageLogID, v))
}

// RelatedUsageLogIDLTE applies the LTE predicate on the "related_usage_log_id" field.
func RelatedUsageLogIDLTE(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldRelatedUsageLogID, v))
}

// RelatedUsageLogIDIsNil applies the IsNil predicate on the "related_usage_log_id" field.
func RelatedUsageLogIDIsNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIsNull(FieldRelatedUsageLogID))
}

// RelatedUsageLogIDNotNil applies the NotNil predicate on the "related_usage_log_id" field.
func RelatedUsageLogIDNotNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotNull(FieldRelatedUsageLogID))
}

// RelatedAPIKeyIDEQ applies the EQ predicate on the "related_api_key_id" field.
func RelatedAPIKeyIDEQ(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldRelatedAPIKeyID, v))
}

// RelatedAPIKeyIDNEQ applies the NEQ predicate on the "related_api_key_id" field.
func RelatedAPIKeyIDNEQ(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldRelatedAPIKeyID, v))
}

// RelatedAPIKeyIDIn applies the In predicate on the "related_api_key_id" field.
func RelatedAPIKeyIDIn(vs ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldRelatedAPIKeyID, vs...))
}

// RelatedAPIKeyIDNotIn applies the NotIn predicate on the "related_api_key_id" field.
func RelatedAPIKeyIDNotIn(vs ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldRelatedAPIKeyID, vs...))
}

// RelatedAPIKeyIDGT applies the GT predicate on the "related_api_key_id" field.
func RelatedAPIKeyIDGT(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldRelatedAPIKeyID, v))
}

// RelatedAPIKeyIDGTE applies the GTE predicate on the "related_api_key_id" field.
func RelatedAPIKeyIDGTE(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldRelatedAPIKeyID, v))
}

// RelatedAPIKeyIDLT applies the LT predicate on the "related_api_key_id" field.
func RelatedAPIKeyIDLT(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldRelatedAPIKeyID, v))
}

// RelatedAPIKeyIDLTE applies the LTE predicate on the "related_api_key_id" field.
func RelatedAPIKeyIDLTE(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldRelatedAPIKeyID, v))
}

// RelatedAPIKeyIDIsNil applies the IsNil predicate on the "related_api_key_id" field.
func RelatedAPIKeyIDIsNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIsNull(FieldRelatedAPIKeyID))
}

// RelatedAPIKeyIDNotNil applies the NotNil predicate on the "related_api_key_id" field.
func RelatedAPIKeyIDNotNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotNull(FieldRelatedAPIKeyID))
}

// RelatedProjectIDEQ applies the EQ predicate on the "related_project_id" field.
func RelatedProjectIDEQ(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldRelatedProjectID, v))
}

// RelatedProjectIDNEQ applies the NEQ predicate on the "related_project_id" field.
func RelatedProjectIDNEQ(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldRelatedProjectID, v))
}

// RelatedProjectIDIn applies the In predicate on the "related_project_id" field.
func RelatedProjectIDIn(vs ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldRelatedProjectID, vs...))
}

// RelatedProjectIDNotIn applies the NotIn predicate on the "related_project_id" field.
func RelatedProjectIDNotIn(vs ...int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldRelatedProjectID, vs...))
}

// RelatedProjectIDGT applies the GT predicate on the "related_project_id" field.
func RelatedProjectIDGT(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldRelatedProjectID, v))
}

// RelatedProjectIDGTE applies the GTE predicate on the "related_project_id" field.
func RelatedProjectIDGTE(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldRelatedProjectID, v))
}

// RelatedProjectIDLT applies the LT predicate on the "related_project_id" field.
func RelatedProjectIDLT(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldRelatedProjectID, v))
}

// RelatedProjectIDLTE applies the LTE predicate on the "related_project_id" field.
func RelatedProjectIDLTE(v int) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldRelatedProjectID, v))
}

// RelatedProjectIDIsNil applies the IsNil predicate on the "related_project_id" field.
func RelatedProjectIDIsNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIsNull(FieldRelatedProjectID))
}

// RelatedProjectIDNotNil applies the NotNil predicate on the "related_project_id" field.
func RelatedProjectIDNotNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotNull(FieldRelatedProjectID))
}

// ConversionRateSnapshotEQ applies the EQ predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotEQ(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldConversionRateSnapshot, v))
}

// ConversionRateSnapshotNEQ applies the NEQ predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotNEQ(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldConversionRateSnapshot, v))
}

// ConversionRateSnapshotIn applies the In predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotIn(vs ...string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldConversionRateSnapshot, vs...))
}

// ConversionRateSnapshotNotIn applies the NotIn predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotNotIn(vs ...string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldConversionRateSnapshot, vs...))
}

// ConversionRateSnapshotGT applies the GT predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotGT(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldConversionRateSnapshot, v))
}

// ConversionRateSnapshotGTE applies the GTE predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotGTE(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldConversionRateSnapshot, v))
}

// ConversionRateSnapshotLT applies the LT predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotLT(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldConversionRateSnapshot, v))
}

// ConversionRateSnapshotLTE applies the LTE predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotLTE(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldConversionRateSnapshot, v))
}

// ConversionRateSnapshotContains applies the Contains predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotContains(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldContains(FieldConversionRateSnapshot, v))
}

// ConversionRateSnapshotHasPrefix applies the HasPrefix predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotHasPrefix(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldHasPrefix(FieldConversionRateSnapshot, v))
}

// ConversionRateSnapshotHasSuffix applies the HasSuffix predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotHasSuffix(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldHasSuffix(FieldConversionRateSnapshot, v))
}

// ConversionRateSnapshotIsNil applies the IsNil predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotIsNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIsNull(FieldConversionRateSnapshot))
}

// ConversionRateSnapshotNotNil applies the NotNil predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotNotNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotNull(FieldConversionRateSnapshot))
}

// ConversionRateSnapshotEqualFold applies the EqualFold predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotEqualFold(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEqualFold(FieldConversionRateSnapshot, v))
}

// ConversionRateSnapshotContainsFold applies the ContainsFold predicate on the "conversion_rate_snapshot" field.
func ConversionRateSnapshotContainsFold(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldContainsFold(FieldConversionRateSnapshot, v))
}

// SettlementStatusEQ applies the EQ predicate on the "settlement_status" field.
func SettlementStatusEQ(v SettlementStatus) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldSettlementStatus, v))
}

// SettlementStatusNEQ applies the NEQ predicate on the "settlement_status" field.
func SettlementStatusNEQ(v SettlementStatus) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldSettlementStatus, v))
}

// SettlementStatusIn applies the In predicate on the "settlement_status" field.
func SettlementStatusIn(vs ...SettlementStatus) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldSettlementStatus, vs...))
}

// SettlementStatusNotIn applies the NotIn predicate on the "settlement_status" field.
func SettlementStatusNotIn(vs ...SettlementStatus) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldSettlementStatus, vs...))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.FieldContainsFold(FieldRemark, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserPointLedgerEntry) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserPointLedgerEntry) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserPointLedgerEntry) predicate.UserPointLedgerEntry {
	return predicate.UserPointLedgerEntry(sql.NotPredicates(p))
}
