// Code generated by ent, DO NOT EDIT.

package relaykey

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the relaykey type in the database.
	Label = "relay_key"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldBalanceMode holds the string denoting the balance_mode field in the database.
	FieldBalanceMode = "balance_mode"
	// FieldDailyRequestLimit holds the string denoting the daily_request_limit field in the database.
	FieldDailyRequestLimit = "daily_request_limit"
	// FieldDailyTokenLimit holds the string denoting the daily_token_limit field in the database.
	FieldDailyTokenLimit = "daily_token_limit"
	// FieldMonthlyCostLimit holds the string denoting the monthly_cost_limit field in the database.
	FieldMonthlyCostLimit = "monthly_cost_limit"
	// FieldConcurrencyLimit holds the string denoting the concurrency_limit field in the database.
	FieldConcurrencyLimit = "concurrency_limit"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldLastUsedAt holds the string denoting the last_used_at field in the database.
	FieldLastUsedAt = "last_used_at"
	// EdgeAPIKey holds the string denoting the api_key edge name in mutations.
	EdgeAPIKey = "api_key"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// EdgeOwnerUser holds the string denoting the owner_user edge name in mutations.
	EdgeOwnerUser = "owner_user"
	// EdgeWallet holds the string denoting the wallet edge name in mutations.
	EdgeWallet = "wallet"
	// EdgeLedgerEntries holds the string denoting the ledger_entries edge name in mutations.
	EdgeLedgerEntries = "ledger_entries"
	// EdgeDailyUsageSummaries holds the string denoting the daily_usage_summaries edge name in mutations.
	EdgeDailyUsageSummaries = "daily_usage_summaries"
	// Table holds the table name of the relaykey in the database.
	Table = "relay_keys"
	// APIKeyTable is the table that holds the api_key relation/edge.
	APIKeyTable = "relay_keys"
	// APIKeyInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeyInverseTable = "api_keys"
	// APIKeyColumn is the table column denoting the api_key relation/edge.
	APIKeyColumn = "api_key_id"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "relay_keys"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// ProductTable is the table that holds the product relation/edge.
	ProductTable = "relay_keys"
	// ProductInverseTable is the table name for the RelayProduct entity.
	// It exists in this package in order to avoid circular dependency with the "relayproduct" package.
	ProductInverseTable = "relay_products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_id"
	// OwnerUserTable is the table that holds the owner_user relation/edge.
	OwnerUserTable = "relay_keys"
	// OwnerUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerUserInverseTable = "users"
	// OwnerUserColumn is the table column denoting the owner_user relation/edge.
	OwnerUserColumn = "owner_user_id"
	// WalletTable is the table that holds the wallet relation/edge.
	WalletTable = "relay_wallets"
	// WalletInverseTable is the table name for the RelayWallet entity.
	// It exists in this package in order to avoid circular dependency with the "relaywallet" package.
	WalletInverseTable = "relay_wallets"
	// WalletColumn is the table column denoting the wallet relation/edge.
	WalletColumn = "relay_key_id"
	// LedgerEntriesTable is the table that holds the ledger_entries relation/edge.
	LedgerEntriesTable = "relay_wallet_ledger_entries"
	// LedgerEntriesInverseTable is the table name for the RelayWalletLedgerEntry entity.
	// It exists in this package in order to avoid circular dependency with the "relaywalletledgerentry" package.
	LedgerEntriesInverseTable = "relay_wallet_ledger_entries"
	// LedgerEntriesColumn is the table column denoting the ledger_entries relation/edge.
	LedgerEntriesColumn = "relay_key_id"
	// DailyUsageSummariesTable is the table that holds the daily_usage_summaries relation/edge.
	DailyUsageSummariesTable = "relay_daily_usage_summaries"
	// DailyUsageSummariesInverseTable is the table name for the RelayDailyUsageSummary entity.
	// It exists in this package in order to avoid circular dependency with the "relaydailyusagesummary" package.
	DailyUsageSummariesInverseTable = "relay_daily_usage_summaries"
	// DailyUsageSummariesColumn is the table column denoting the daily_usage_summaries relation/edge.
	DailyUsageSummariesColumn = "relay_key_id"
)

// Columns holds all SQL columns for relaykey fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldAPIKeyID,
	FieldProjectID,
	FieldProductID,
	FieldOwnerUserID,
	FieldDisplayName,
	FieldStatus,
	FieldBalanceMode,
	FieldDailyRequestLimit,
	FieldDailyTokenLimit,
	FieldMonthlyCostLimit,
	FieldConcurrencyLimit,
	FieldExpiresAt,
	FieldLastUsedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	Policy       ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive    Status = "active"
	StatusSuspended Status = "suspended"
	StatusExhausted Status = "exhausted"
	StatusArchived  Status = "archived"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusSuspended, StatusExhausted, StatusArchived:
		return nil
	default:
		return fmt.Errorf("relaykey: invalid enum value for status field: %q", s)
	}
}

// BalanceMode defines the type for the "balance_mode" enum field.
type BalanceMode string

// BalanceModePrepaid is the default value of the BalanceMode enum.
const DefaultBalanceMode = BalanceModePrepaid

// BalanceMode values.
const (
	BalanceModePrepaid   BalanceMode = "prepaid"
	BalanceModeQuotaOnly BalanceMode = "quota_only"
)

func (bm BalanceMode) String() string {
	return string(bm)
}

// BalanceModeValidator is a validator for the "balance_mode" field enum values. It is called by the builders before save.
func BalanceModeValidator(bm BalanceMode) error {
	switch bm {
	case BalanceModePrepaid, BalanceModeQuotaOnly:
		return nil
	default:
		return fmt.Errorf("relaykey: invalid enum value for balance_mode field: %q", bm)
	}
}

// OrderOption defines the ordering options for the RelayKey queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByBalanceMode orders the results by the balance_mode field.
func ByBalanceMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceMode, opts...).ToFunc()
}

// ByDailyRequestLimit orders the results by the daily_request_limit field.
func ByDailyRequestLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyRequestLimit, opts...).ToFunc()
}

// ByDailyTokenLimit orders the results by the daily_token_limit field.
func ByDailyTokenLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyTokenLimit, opts...).ToFunc()
}

// ByMonthlyCostLimit orders the results by the monthly_cost_limit field.
func ByMonthlyCostLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyCostLimit, opts...).ToFunc()
}

// ByConcurrencyLimit orders the results by the concurrency_limit field.
func ByConcurrencyLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrencyLimit, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByLastUsedAt orders the results by the last_used_at field.
func ByLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedAt, opts...).ToFunc()
}

// ByAPIKeyField orders the results by api_key field.
func ByAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByProductField orders the results by product field.
func ByProductField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductStep(), sql.OrderByField(field, opts...))
	}
}

// ByOwnerUserField orders the results by owner_user field.
func ByOwnerUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByWalletField orders the results by wallet field.
func ByWalletField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWalletStep(), sql.OrderByField(field, opts...))
	}
}

// ByLedgerEntriesCount orders the results by ledger_entries count.
func ByLedgerEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLedgerEntriesStep(), opts...)
	}
}

// ByLedgerEntries orders the results by ledger_entries terms.
func ByLedgerEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLedgerEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDailyUsageSummariesCount orders the results by daily_usage_summaries count.
func ByDailyUsageSummariesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDailyUsageSummariesStep(), opts...)
	}
}

// ByDailyUsageSummaries orders the results by daily_usage_summaries terms.
func ByDailyUsageSummaries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDailyUsageSummariesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, APIKeyTable, APIKeyColumn),
	)
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
	)
}
func newOwnerUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerUserTable, OwnerUserColumn),
	)
}
func newWalletStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WalletInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, WalletTable, WalletColumn),
	)
}
func newLedgerEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LedgerEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LedgerEntriesTable, LedgerEntriesColumn),
	)
}
func newDailyUsageSummariesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DailyUsageSummariesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DailyUsageSummariesTable, DailyUsageSummariesColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e BalanceMode) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *BalanceMode) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = BalanceMode(str)
	if err := BalanceModeValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid BalanceMode", str)
	}
	return nil
}
