// Code generated by ent, DO NOT EDIT.

package relaykey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldDeletedAt, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldAPIKeyID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldProjectID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldProductID, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldOwnerUserID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldDisplayName, v))
}

// DailyRequestLimit applies equality check predicate on the "daily_request_limit" field. It's identical to DailyRequestLimitEQ.
func DailyRequestLimit(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldDailyRequestLimit, v))
}

// DailyTokenLimit applies equality check predicate on the "daily_token_limit" field. It's identical to DailyTokenLimitEQ.
func DailyTokenLimit(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldDailyTokenLimit, v))
}

// MonthlyCostLimit applies equality check predicate on the "monthly_cost_limit" field. It's identical to MonthlyCostLimitEQ.
func MonthlyCostLimit(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldMonthlyCostLimit, v))
}

// ConcurrencyLimit applies equality check predicate on the "concurrency_limit" field. It's identical to ConcurrencyLimitEQ.
func ConcurrencyLimit(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldConcurrencyLimit, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldExpiresAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLTE(FieldDeletedAt, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldProductID, vs...))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDIsNil applies the IsNil predicate on the "owner_user_id" field.
func OwnerUserIDIsNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIsNull(FieldOwnerUserID))
}

// OwnerUserIDNotNil applies the NotNil predicate on the "owner_user_id" field.
func OwnerUserIDNotNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotNull(FieldOwnerUserID))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldContainsFold(FieldDisplayName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldStatus, vs...))
}

// BalanceModeEQ applies the EQ predicate on the "balance_mode" field.
func BalanceModeEQ(v BalanceMode) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldBalanceMode, v))
}

// BalanceModeNEQ applies the NEQ predicate on the "balance_mode" field.
func BalanceModeNEQ(v BalanceMode) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldBalanceMode, v))
}

// BalanceModeIn applies the In predicate on the "balance_mode" field.
func BalanceModeIn(vs ...BalanceMode) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldBalanceMode, vs...))
}

// BalanceModeNotIn applies the NotIn predicate on the "balance_mode" field.
func BalanceModeNotIn(vs ...BalanceMode) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldBalanceMode, vs...))
}

// DailyRequestLimitEQ applies the EQ predicate on the "daily_request_limit" field.
func DailyRequestLimitEQ(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldDailyRequestLimit, v))
}

// DailyRequestLimitNEQ applies the NEQ predicate on the "daily_request_limit" field.
func DailyRequestLimitNEQ(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldDailyRequestLimit, v))
}

// DailyRequestLimitIn applies the In predicate on the "daily_request_limit" field.
func DailyRequestLimitIn(vs ...int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldDailyRequestLimit, vs...))
}

// DailyRequestLimitNotIn applies the NotIn predicate on the "daily_request_limit" field.
func DailyRequestLimitNotIn(vs ...int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldDailyRequestLimit, vs...))
}

// DailyRequestLimitGT applies the GT predicate on the "daily_request_limit" field.
func DailyRequestLimitGT(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGT(FieldDailyRequestLimit, v))
}

// DailyRequestLimitGTE applies the GTE predicate on the "daily_request_limit" field.
func DailyRequestLimitGTE(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGTE(FieldDailyRequestLimit, v))
}

// DailyRequestLimitLT applies the LT predicate on the "daily_request_limit" field.
func DailyRequestLimitLT(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLT(FieldDailyRequestLimit, v))
}

// DailyRequestLimitLTE applies the LTE predicate on the "daily_request_limit" field.
func DailyRequestLimitLTE(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLTE(FieldDailyRequestLimit, v))
}

// DailyRequestLimitIsNil applies the IsNil predicate on the "daily_request_limit" field.
func DailyRequestLimitIsNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIsNull(FieldDailyRequestLimit))
}

// DailyRequestLimitNotNil applies the NotNil predicate on the "daily_request_limit" field.
func DailyRequestLimitNotNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotNull(FieldDailyRequestLimit))
}

// DailyTokenLimitEQ applies the EQ predicate on the "daily_token_limit" field.
func DailyTokenLimitEQ(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldDailyTokenLimit, v))
}

// DailyTokenLimitNEQ applies the NEQ predicate on the "daily_token_limit" field.
func DailyTokenLimitNEQ(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldDailyTokenLimit, v))
}

// DailyTokenLimitIn applies the In predicate on the "daily_token_limit" field.
func DailyTokenLimitIn(vs ...int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldDailyTokenLimit, vs...))
}

// DailyTokenLimitNotIn applies the NotIn predicate on the "daily_token_limit" field.
func DailyTokenLimitNotIn(vs ...int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldDailyTokenLimit, vs...))
}

// DailyTokenLimitGT applies the GT predicate on the "daily_token_limit" field.
func DailyTokenLimitGT(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGT(FieldDailyTokenLimit, v))
}

// DailyTokenLimitGTE applies the GTE predicate on the "daily_token_limit" field.
func DailyTokenLimitGTE(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGTE(FieldDailyTokenLimit, v))
}

// DailyTokenLimitLT applies the LT predicate on the "daily_token_limit" field.
func DailyTokenLimitLT(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLT(FieldDailyTokenLimit, v))
}

// DailyTokenLimitLTE applies the LTE predicate on the "daily_token_limit" field.
func DailyTokenLimitLTE(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLTE(FieldDailyTokenLimit, v))
}

// DailyTokenLimitIsNil applies the IsNil predicate on the "daily_token_limit" field.
func DailyTokenLimitIsNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIsNull(FieldDailyTokenLimit))
}

// DailyTokenLimitNotNil applies the NotNil predicate on the "daily_token_limit" field.
func DailyTokenLimitNotNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotNull(FieldDailyTokenLimit))
}

// MonthlyCostLimitEQ applies the EQ predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitEQ(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldMonthlyCostLimit, v))
}

// MonthlyCostLimitNEQ applies the NEQ predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitNEQ(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldMonthlyCostLimit, v))
}

// MonthlyCostLimitIn applies the In predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitIn(vs ...string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldMonthlyCostLimit, vs...))
}

// MonthlyCostLimitNotIn applies the NotIn predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitNotIn(vs ...string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldMonthlyCostLimit, vs...))
}

// MonthlyCostLimitGT applies the GT predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitGT(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGT(FieldMonthlyCostLimit, v))
}

// MonthlyCostLimitGTE applies the GTE predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitGTE(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGTE(FieldMonthlyCostLimit, v))
}

// MonthlyCostLimitLT applies the LT predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitLT(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLT(FieldMonthlyCostLimit, v))
}

// MonthlyCostLimitLTE applies the LTE predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitLTE(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLTE(FieldMonthlyCostLimit, v))
}

// MonthlyCostLimitContains applies the Contains predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitContains(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldContains(FieldMonthlyCostLimit, v))
}

// MonthlyCostLimitHasPrefix applies the HasPrefix predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitHasPrefix(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldHasPrefix(FieldMonthlyCostLimit, v))
}

// MonthlyCostLimitHasSuffix applies the HasSuffix predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitHasSuffix(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldHasSuffix(FieldMonthlyCostLimit, v))
}

// MonthlyCostLimitIsNil applies the IsNil predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitIsNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIsNull(FieldMonthlyCostLimit))
}

// MonthlyCostLimitNotNil applies the NotNil predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitNotNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotNull(FieldMonthlyCostLimit))
}

// MonthlyCostLimitEqualFold applies the EqualFold predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitEqualFold(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEqualFold(FieldMonthlyCostLimit, v))
}

// MonthlyCostLimitContainsFold applies the ContainsFold predicate on the "monthly_cost_limit" field.
func MonthlyCostLimitContainsFold(v string) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldContainsFold(FieldMonthlyCostLimit, v))
}

// ConcurrencyLimitEQ applies the EQ predicate on the "concurrency_limit" field.
func ConcurrencyLimitEQ(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitNEQ applies the NEQ predicate on the "concurrency_limit" field.
func ConcurrencyLimitNEQ(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitIn applies the In predicate on the "concurrency_limit" field.
func ConcurrencyLimitIn(vs ...int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldConcurrencyLimit, vs...))
}

// ConcurrencyLimitNotIn applies the NotIn predicate on the "concurrency_limit" field.
func ConcurrencyLimitNotIn(vs ...int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldConcurrencyLimit, vs...))
}

// ConcurrencyLimitGT applies the GT predicate on the "concurrency_limit" field.
func ConcurrencyLimitGT(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGT(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitGTE applies the GTE predicate on the "concurrency_limit" field.
func ConcurrencyLimitGTE(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGTE(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitLT applies the LT predicate on the "concurrency_limit" field.
func ConcurrencyLimitLT(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLT(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitLTE applies the LTE predicate on the "concurrency_limit" field.
func ConcurrencyLimitLTE(v int64) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLTE(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitIsNil applies the IsNil predicate on the "concurrency_limit" field.
func ConcurrencyLimitIsNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIsNull(FieldConcurrencyLimit))
}

// ConcurrencyLimitNotNil applies the NotNil predicate on the "concurrency_limit" field.
func ConcurrencyLimitNotNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotNull(FieldConcurrencyLimit))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotNull(FieldExpiresAt))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.RelayKey {
	return predicate.RelayKey(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.RelayKey {
	return predicate.RelayKey(sql.FieldNotNull(FieldLastUsedAt))
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.RelayProduct) predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwnerUser applies the HasEdge predicate on the "owner_user" edge.
func HasOwnerUser() predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerUserTable, OwnerUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerUserWith applies the HasEdge predicate on the "owner_user" edge with a given conditions (other predicates).
func HasOwnerUserWith(preds ...predicate.User) predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := newOwnerUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWallet applies the HasEdge predicate on the "wallet" edge.
func HasWallet() predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, WalletTable, WalletColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWalletWith applies the HasEdge predicate on the "wallet" edge with a given conditions (other predicates).
func HasWalletWith(preds ...predicate.RelayWallet) predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := newWalletStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLedgerEntries applies the HasEdge predicate on the "ledger_entries" edge.
func HasLedgerEntries() predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LedgerEntriesTable, LedgerEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerEntriesWith applies the HasEdge predicate on the "ledger_entries" edge with a given conditions (other predicates).
func HasLedgerEntriesWith(preds ...predicate.RelayWalletLedgerEntry) predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := newLedgerEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDailyUsageSummaries applies the HasEdge predicate on the "daily_usage_summaries" edge.
func HasDailyUsageSummaries() predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DailyUsageSummariesTable, DailyUsageSummariesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDailyUsageSummariesWith applies the HasEdge predicate on the "daily_usage_summaries" edge with a given conditions (other predicates).
func HasDailyUsageSummariesWith(preds ...predicate.RelayDailyUsageSummary) predicate.RelayKey {
	return predicate.RelayKey(func(s *sql.Selector) {
		step := newDailyUsageSummariesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelayKey) predicate.RelayKey {
	return predicate.RelayKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelayKey) predicate.RelayKey {
	return predicate.RelayKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelayKey) predicate.RelayKey {
	return predicate.RelayKey(sql.NotPredicates(p))
}
